### ISSUE TITLE
Typesafe Graphql Client hangs inside a uni

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#1175]
I have a really strange problem with the typesafe graphql client. It only appears for us under windows and kubernetes, but not under linux (ubuntu, wsl).
If you are inside a uni and call the graphql client, it just hangs forever in the post Method.

Something like this, fails:
```
findById(client, id).map(f->{
            api.test();
            return f;
        });
```

This works:
```
        api.test();

        return findById(client, id).map(f->{
            return f;
        });
```

Reproducer for windows:
[code-with-quarkus-mutiny-graphql-client.zip](https://github.com/smallrye/smallrye-graphql/files/7597505/code-with-quarkus-mutiny-graphql-client.zip)

The reproducer needs Docker.

Run the following query against the graphql server:
`query a{fruit(id:1){id}}`

The reproducer should return an exception since there is no graphql service where it can connect, but it just hangs. If you run the call outside the uni, it works for us as expected.

In Kubernetes, we get a warning like this, but not under windows;
```
2021-11-24 13:26:05,475 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 13784993 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
    at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
    at java.base@11.0.13/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.13/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
    at java.base@11.0.13/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
    at java.base@11.0.13/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
    at java.base@11.0.13/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)
    at io.smallrye.graphql.client.typesafe.vertx.VertxTypesafeGraphQLClientProxy.post(VertxTypesafeGraphQLClientProxy.java:158)
    at io.smallrye.graphql.client.typesafe.vertx.VertxTypesafeGraphQLClientProxy.invoke(VertxTypesafeGraphQLClientProxy.java:69)
    at io.smallrye.graphql.client.typesafe.vertx.VertxTypesafeGraphQLClientBuilder.invoke(VertxTypesafeGraphQLClientBuilder.java:120)
    at io.smallrye.graphql.client.typesafe.vertx.VertxTypesafeGraphQLClientBuilder.lambda$build$0(VertxTypesafeGraphQLClientBuilder.java:86)
    at io.smallrye.graphql.client.typesafe.vertx.VertxTypesafeGraphQLClientBuilder$$Lambda$1414/0x00000008408d9c40.invoke(Unknown Source)
```

**Comment by robp94** [comment]
We looked more into this and found out that if you use `.emitOn(Infrastructure.getDefaultWorkerPool())` it works as it should.
Tried it only with the `@Blocking` annotation and `runSubscriptionOn` which did not work.
Not sure if you can or need to change anything, but maybe mention this in the documentation?

**Comment by jmartisk** [comment]
Doing a long blocking operation in an event loop thread is definitely wrong, but I am puzzled by the hang that you're describing. Unfortunately I don't have any suitable Windows machine to try it :/
Does the hang happen always, or, only in the situation that you described as "there is no graphql service where it can connect"?

Btw., in the upcoming version 1.4.0 we will allow typesafe clients to simply wrap any return type into a `Uni` and thus call the operation asynchronously. This should help avoid the problem with using a client inside a `Uni`

**Comment by robp94** [comment]
It happened always. Was just an easy reproducer. Normally we mark a blocking method with the annotation. But here it did not work for us.

Ok looking forward to the update.

**Comment by jmartisk** [comment]
Adding `@Blocking` makes your method itself run on a worker thread, but if you spawn asynchronous code within that method, that code might still end up executing on an event loop thread, which is what apparently happened in your case. 
`.emitOn(Infrastructure.getDefaultWorkerPool())` seems to me like the correct solution if that code is blocking

**Comment by robp94** [comment]
Thx for the explanation, fell free to close the issue.
