### ISSUE TITLE
Memory leak in UniDataFetcher

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#1307]
There seems to be a memory leak in the CDI integration for UniDataFetcher when some of the beans has `Dependent` scope.
If one of the beans is a rest client there also seems to be a connection leak, where connections are left in state `CLOSE_WAIT`.

When running [this sample app](https://github.com/computerlove/smallrye-graphql-leak) (running the one available graphql operation, getting all fields, in graphql-ui) `lsof -p PID` shows lines like this
```
java    15125 user   54u     IPv6          177551410       0t0       TCP myhost:39456->ec2-3-221-189-238.compute-1.amazonaws.com:https (CLOSE_WAIT)
```
Taking a heap dump of the application will show that there are many instances of `io.quarkus.arc.impl.EagerInstanceHandle`, containing 
```
instance = {GQL_Subclass@X} 
bean = {GQL_Bean@Y} 
```
and 
```
instance = {Other_Subclass@Z} 
bean = {Other_Bean@ZZ} 
```
Setting a stacktrace in `CreationalContextImpl.addDependentInstance(...):43` looks like this after a few requests:
![debugger](https://user-images.githubusercontent.com/769579/157397832-1291ac22-f2c3-43a8-9376-08fad3fa33a6.png)

The stack at this point is 
```
at io.quarkus.arc.impl.CreationalContextImpl.addDependentInstance(CreationalContextImpl.java:43)
at io.quarkus.arc.impl.CreationalContextImpl.addDependentInstance(CreationalContextImpl.java:36)
at io.quarkus.arc.impl.CreationalContextImpl.addDependencyToParent(CreationalContextImpl.java:123)
at org.acme.GQL_Bean.get(Unknown Source)
at org.acme.GQL_Bean.get(Unknown Source)
at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:223)
at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:209)
at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:95)
at io.smallrye.graphql.cdi.CdiLookupService.getInstance(CdiLookupService.java:27)
at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:85)
at io.smallrye.graphql.execution.datafetcher.UniDataFetcher.invokeAndTransform(UniDataFetcher.java:41)
at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:53)
at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
at graphql.execution.Execution.executeOperation(Execution.java:159)
at graphql.execution.Execution.execute(Execution.java:105)
at graphql.GraphQL.execute(GraphQL.java:613)
at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:538)
at graphql.GraphQL.executeAsync(GraphQL.java:502)
at graphql.GraphQL.execute(GraphQL.java:433)
at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:126)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:299)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:113)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:73)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:66)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:48)
at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:23)
at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
...
```

If all beans are changed to `ApplicationScoped` the leak seems to go away.

**Comment by computerlove** [comment]
Not sure if this is the correct way to do it, but tested the following change, and it seems to do what I wanted:
```java
@RequestScoped
public class RequestResources {
    private final List<InstanceAndObject> instances = new ArrayList<>();

    public void add(Instance instance, Object object) {
        instances.add(new InstanceAndObject(instance, object));
    }

    @PreDestroy
    public void clean() {
        for (InstanceAndObject io : instances) {
            io.instance.destroy(io.object);
        }
    }

    private static class InstanceAndObject {
        final Instance instance;
        final Object object;

        private InstanceAndObject(Instance instance, Object object) {
            this.instance = instance;
            this.object = object;
        }
    }
}
```

```java
public class CdiLookupService implements LookupService {
   ...
    @Override
    public Object getInstance(Class<?> declaringClass) {
        Instance<?> instance = CDI.current().select(declaringClass);
        Object o = instance.get();
        RequestResources requestResources = CDI.current().select(RequestResources.class).get();
        requestResources.add(instance, o);
        return o;
    }
   ...
}
```

**Comment by jmartisk** [comment]
Hmmm, by doing this change you are basically turning all GraphQLApi classes to request scoped beans, because you destroy them after the request. Maybe it would be acceptable if you also checked the scope of each bean before adding it to `RequestResources`, but then how would we handle potential custom CDI scopes (where we don't know when to destroy the instance)?.... 
I'll have a little dig into it and perhaps I will get an idea

**Comment by computerlove** [comment]
Turning all GraphQLApi classes to request scoped beans was not really what I wanted. :p

It looks like both annotating components with `@RequestScoped`, and `@Singleton` and `@ApplicationScoped` avoids the problem.

**Comment by jmartisk** [comment]
I have an idea how to handle it, we will just need to update the code so that any Dependent-scoped instance used by the CdiLookupService will get destroyed right after use. I'll submit a PR soon
