### ISSUE TITLE
JDK17: local DNS failure in GraphQL Client → vertx → netty

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#1589]
We try to run our application on WildFly 26.1.1 on JDK17, but the GraphQL Client calls to servers in our local network (using an internal `server.lan` domain) fail with a stacktrace containing something like this:

```
Caused by: java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'xxx.server.lan' and search domain query for configured domains failed as well: [server.lan]
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at io.smallrye.graphql.client.vertx@4.1.2//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.postSync(VertxTypesafeGraphQLClientProxy.java:384)
    ... 207 more
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'xxx.server.lan' and search domain query for configured domains failed as well: [server.lan]
    at io.netty.netty-resolver-dns@4.1.76.Final//io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
    at io.netty.netty-resolver-dns@4.1.76.Final//io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
    at io.netty.netty-resolver-dns@4.1.76.Final//io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
    at io.netty.netty-resolver-dns@4.1.76.Final//io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
```

Digging deeper, we found this log from Netty:

```
java.lang.IllegalAccessException: class org.jboss.as.naming.InitialContext cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to unnamed module @32a32c84
```

So this seems to be a problem with Netty, which is used by vert.x, which is used by the GraphQL Client. Maybe updating some dependencies could suffice to fix this.

**Comment by jmartisk** [comment]
The client is running inside a WildFly server instance right? Just thinking, would it then help if you started WildFly with the  JAVA_OPTS env variable set to `--add-exports=jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED`?

**Comment by t1** [comment]
Yes, something like this is what we are doing as a workaround. But it would be nice to have it actually fixed, esp. when it's just bumping some dependency 😜

**Comment by jmartisk** [comment]
The class not being to access something is `org.jboss.as.naming.InitialContext`, which is a WildFly-internal class. Thus I would think this is a problem in WildFly itself.

**Comment by ftrossbach** [comment]
Adding `--add-exports=jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED` to the Wildfly JAVA_OPTS worked indeed

**Comment by jmartisk** [comment]
I'd suggest reporting an issue in the WFLY tracker (https://issues.redhat.com/projects/WFLY/issues/)  and asking the WF team their opinion. IIUC this should be reproducible without GraphQL clients, with anything that uses Netty for DNS, and WildFly contains Netty bundled in.

**Comment by ftrossbach** [comment]
Openend https://issues.redhat.com/browse/WFLY-17127
