### ISSUE TITLE
NPE when processing a invalid query

### ISSUE THREAD

**Issue by roggenbrot** [smallrye/smallrye-graphql#1666]
When a invalid query is processed (e.g. json syntax error) a NPE exception is thrown

```
2023-01-03 13:41:19,784 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /graphql failed, error id: 8c1a8338-36d6-42b9-bbf7-c83cdbfb4366-1: java.lang.NullPointerException: Cannot invoke "graphql.language.Document.getDefinitionsOfType(java.lang.Class)" because "document" is null
	at io.smallrye.graphql.execution.context.SmallRyeContextManager.getRequestedOperationTypes(SmallRyeContextManager.java:253)
	at io.smallrye.graphql.execution.context.SmallRyeContextManager.populateFromExecutionInput(SmallRyeContextManager.java:102)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:155)
	at io.smallrye.graphql.execution.ExecutionService.executeAsync(ExecutionService.java:105)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:366)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:127)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:87)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handleWithIdentity(SmallRyeGraphQLAbstractHandler.java:95)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:76)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLAbstractHandler.handle(SmallRyeGraphQLAbstractHandler.java:30)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:140)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:358)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:335)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.http.impl.HttpEventHandler.handleEnd(HttpEventHandler.java:76)
	at io.vertx.core.http.impl.Http1xServerRequest.onEnd(Http1xServerRequest.java:581)
	at io.vertx.core.http.impl.Http1xServerRequest.lambda$pendingQueue$1(Http1xServerRequest.java:130)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:239)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:129)
	at io.vertx.core.http.impl.Http1xServerRequest.handleEnd(Http1xServerRequest.java:562)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:76)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:153)
	at io.vertx.core.http.impl.Http1xServerConnection.onEnd(Http1xServerConnection.java:191)
	at io.vertx.core.http.impl.Http1xServerConnection.onContent(Http1xServerConnection.java:181)
	at io.vertx.core.http.impl.Http1xServerConnection.handleOther(Http1xServerConnection.java:161)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:149)
```

This seems to be caused by missing null check of the document returned by the document supplier in https://github.com/smallrye/smallrye-graphql/blob/9cefecb754da67af0da8d2ed714bb7e88878baf1/server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContextManager.java#L252

which returns null if the query could not be parsed

https://github.com/smallrye/smallrye-graphql/blob/9cefecb754da67af0da8d2ed714bb7e88878baf1/server/implementation/src/main/java/io/smallrye/graphql/execution/context/DocumentSupplier.java#L33

## Reproduce

```java
@Inject
@GraphQLClient
DynamicGraphQLClient client;
...
var response = client.executeSync(
  document(
    operation(
      field("test",
          List.of(arg("uuid", UUID.fromString("a0a0683e-d773-411b-a382-0591a09d9e0f"))), // Adding a UUID object instead of a string causes the invalid query json
          field("uuid")
      )
     )
  )
)

```

**Comment by phillip-kruger** [comment]
@jmartisk can you have a look ?

**Comment by jmartisk** [comment]
Sure.

**Comment by roggenbrot** [comment]
Should I create a seperate issue for the problem in DynamicGraphQLClient https://github.com/smallrye/smallrye-graphql/blob/9cefecb754da67af0da8d2ed714bb7e88878baf1/client/implementation/src/main/java/io/smallrye/graphql/client/impl/core/utils/ValueFormatter.java#L13-L36


that caused the issue (No support for lists/Iterable, UUIDs are are added unquoted)

**Comment by jmartisk** [comment]
Yeah if the dynamic client allows you to build an invalid request via its DSL, that's a separate issue, please report it.

**Comment by t1** [comment]
Still, the handling of invalid queries should be more robust, shouldn't it?

**Comment by jmartisk** [comment]
Of course, that's what we're planning to do with this issue, no? On the server side, if a parsing error occurs, throw something reasonable instead of NPE.

**Comment by jmartisk** [comment]
@mskacelik is working on this
