### ISSUE TITLE
Generics on Mutations produce random / wrong Types in Schema

### ISSUE THREAD

**Issue by tacu90** [smallrye/smallrye-graphql#1809]
Hi everyone,

I'm trying to create an Interface that describes some queries / mutations that all my GraphQL Api Resources should implement. I'm using Generics to define the methods return and parameter types.

It seems that it is working as expected for Queries. The Return Type is always correctly set how it is defined in the implementing ressource class.
But it seems to be random if mutations are getting the correct / concrete Type or the abstract type.

Example:

```java
public abstract class Character {
  public String name;
  public String surname;
}
```
```java
@Input("HeroInput")
public class Hero extends Character {

  public String name;
  public String surname;
  public Double height;
  public Integer mass;
  public Boolean darkSide;
}
```

```java
public interface CharacterResource<T extends Character> {
  List<T> getAll();

  T add(T character);

  T remove(T character);

  T update(T character);

  T doSomething();
}
```

```java
@GraphQLApi
public class HeroResource implements CharacterResource<Hero> {

  @Override
  @Query("heroes")
  public List<Hero> getAll() {
    return null;
  }

  @Override
  @Mutation("addHero")
  public Hero add(@Name("hero") Hero character) {
    return null;
  }

  @Override
  @Mutation("removeHero")
  public Hero remove(@Name("hero") Hero character) {
    return null;
  }

  @Override
  @Mutation("updateHero")
  public Hero update(@Name("hero") Hero character) {
    return null;
  }

  @Override
  @Mutation("doSomething")
  public Hero doSomething() {
    return null;
  }

}
```

This is resulting in the following schema. Note that only updateHero has the correct concrete Types "HeroInput" and "Hero". The other three Mutations are using "CharacterInput" and "Character". This is changing everytime i restart the project.
I would expect that all Mutations are using "HeroInput" and "Hero" as their types.
```
type Character {
  name: String
  surname: String
}

type Hero {
  darkSide: Boolean
  height: Float
  mass: Int
  name: String
  surname: String
}

"Mutation root"
type Mutation {
  addHero(hero: CharacterInput): Character
  doSomething: Character
  removeHero(hero: CharacterInput): Character
  updateHero(hero: HeroInput): Hero
}

"Query root"
type Query {
  heroes: [Hero]
}

input CharacterInput {
  name: String
  surname: String
}

input HeroInput {
  darkSide: Boolean
  height: Float
  mass: Int
  name: String
  surname: String
}
```

Reproducer:
[graphQLInterfaceBug.zip](https://github.com/smallrye/smallrye-graphql/files/11274230/graphQLInterfaceBug.zip)

PS: I also need to add "@name" to all Mutation Parameters. Without them, there is an exception at startup:

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 14 more
Caused by: graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was 'null'
	at graphql.Assert.assertValidName(Assert.java:117)
	at graphql.schema.GraphQLArgument.<init>(GraphQLArgument.java:74)
	at graphql.schema.GraphQLArgument.<init>(GraphQLArgument.java:47)
	at graphql.schema.GraphQLArgument$Builder.build(GraphQLArgument.java:511)
	at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLArgument(Bootstrap.java:953)
	at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLArguments(Bootstrap.java:904)
	at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLFieldDefinitionFromOperation(Bootstrap.java:650)
	at io.smallrye.graphql.bootstrap.Bootstrap.addRootObject(Bootstrap.java:309)
	at io.smallrye.graphql.bootstrap.Bootstrap.addMutations(Bootstrap.java:274)
	at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:170)
	at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:119)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:52)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:42)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:32)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:27)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(Unknown Source)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:30)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService1691419614.deploy_2(Unknown Source)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService1691419614.deploy(Unknown Source)
	... 15 more
```

Used Version:
Java 11
Quarkus 2.16.6.Final
smallrye-graphql 1.9.5

**Comment by t1** [comment]
Random behaviour sounds scary, actually. I'll take a look.

**Comment by t1** [comment]
I can reproduce it on Quarkus 2 and 3 as well as on WildFly 26 and 27... even when I remove the `Ally` class (which has an annotation `@Input("CharacterInput")`)

**Comment by phillip-kruger** [comment]
@t1 Are you looking to fix it ?

**Comment by t1** [comment]
I considered it, but I need to get so much on my list, I won't be able to. I think it must be somewhere quite deep inside, so I'm sure you would be much faster, @phillip-kruger 😁

**Comment by phillip-kruger** [comment]
@jmartisk ? You up for it ?
