### ISSUE TITLE
Array of primitive scalar type not supported

### ISSUE THREAD

**Issue by thejibz** [smallrye/smallrye-graphql#196]
Version of smallrye-graphql-servlet: 1.0.1

I noticed that only the "Object version" of scalar types are working when using arrays: Integer[], Float[], Double[]... . 
If you try to use the "Primitive version" (int[], float[], boolean[]) you get an error.

Only exception is char[] that works (also Character[] is working).

Java Code to reproduce:
```
public class IntArrayHolder {
    private int[] intPrimitiveArray;
    private Integer[] intObjectArray;

    public IntArrayHolder() {
    }

    public int[] getIntPrimitiveArray() {
        return intPrimitiveArray;
    }

    public void setIntPrimitiveArray(int[] intPrimitiveArray) {
        this.intPrimitiveArray = intPrimitiveArray;
    }

    public Integer[] getIntObjectArray() {
        return intObjectArray;
    }

    public void setIntObjectArray(Integer[] intObjectArray) {
        this.intObjectArray = intObjectArray;
    }
} 
```

And for the API part:
```
    @Query
    public IntArrayHolder intArrayHolder(IntArrayHolder intArrayHolder) {
        return intArrayHolder;
    }
```

GraphQL request:
```
query {
  intArrayHolder(intArrayHolder:{
    intObjectArray:[123, 456, 789],
    intPrimitiveArray: [123, 456, 789]
  }) {
    intObjectArray
    intPrimitiveArray
  }
}
```

GraphQL output:
```
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "intArrayHolder"
      ],
      "extensions": {
        "exception": "java.lang.ClassCastException",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "intArrayHolder": null
  }
}
```

Java stacktrace:
```
16:40:01,292 ERROR [io.smallrye.graphql.execution.error.ExceptionHandler] (default task-1) Data Fetching Error: java.lang.ClassCastException: class [I cannot be cast to class [Ljava.lang.Object; ([I and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.recursiveTransformArray(AbstractHelper.java:110)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.recursiveTransform(AbstractHelper.java:65)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.ArgumentHelper.correctComplexObjectFromMap(ArgumentHelper.java:200)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.ArgumentHelper.correctObjectClass(ArgumentHelper.java:162)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.ArgumentHelper.afterRecursiveTransform(ArgumentHelper.java:144)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.recursiveTransform(AbstractHelper.java:78)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.ArgumentHelper.getArgument(ArgumentHelper.java:101)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.helper.ArgumentHelper.getArguments(ArgumentHelper.java:64)
	at deployment.server.war//io.smallrye.graphql.execution.datafetcher.ReflectionDataFetcher.get(ReflectionDataFetcher.java:86)
	at deployment.server.war//graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272)
	at deployment.server.war//graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:200)
	at deployment.server.war//graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
[ ... ]
```

**Comment by phillip-kruger** [comment]
Thanks @thejibz . (I accept Pull requests ;) )

**Comment by thejibz** [comment]
Hehe, yes for pull requests but for now I focus on the client part and I log the issues I see.

**Comment by phillip-kruger** [comment]
:) Thanks for the bug, I'll look at it a.s.a.p

**Comment by ybroeker** [comment]
Just submitted a PR, hope you haven't invested any time yet :)
