### ISSUE TITLE
NPE for Dynamic Headers 

### ISSUE THREAD

**Issue by karenmnyv** [smallrye/smallrye-graphql#1970]
We've upgraded Quarkus and went from Smallrye-GraphQL 2.3 to 2.5, and are experiences a NPE when the client tries to generate a request.

We are using DynamicGraphQLClient with url and static header as config.

This is the stacktrace
```
2023-11-15T10:58:04.013+0100 ef2a3fcba86b371188ccde7c56b50a51 ERROR io.smallrye.graphql SRGQL012000: Data Fetching Error: java.lang.NullPointerException: Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because the return value of "io.smallrye.graphql.client.impl.GraphQLClientConfiguration.getDynamicHeaders()" is null
	at io.smallrye.graphql.client.vertx.dynamic.VertxDynamicGraphQLClientBuilder.applyConfig(VertxDynamicGraphQLClientBuilder.java:180)
	at io.smallrye.graphql.client.vertx.dynamic.VertxDynamicGraphQLClientBuilder.build(VertxDynamicGraphQLClientBuilder.java:136)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients.lambda$getClient$0(NamedDynamicClients.java:41)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients.getClient(NamedDynamicClients.java:40)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients_ProducerMethod_getClient_3386b9d9af6f6050f99a5905b45d131bf53c6158_Bean.doCreate(Unknown Source)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients_ProducerMethod_getClient_3386b9d9af6f6050f99a5905b45d131bf53c6158_Bean.create(Unknown Source)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients_ProducerMethod_getClient_3386b9d9af6f6050f99a5905b45d131bf53c6158_Bean.get(Unknown Source)
	at io.smallrye.graphql.client.impl.dynamic.cdi.NamedDynamicClients_ProducerMethod_getClient_3386b9d9af6f6050f99a5905b45d131bf53c6158_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
	at no.nte.bedriftsportal.fjutt.Hark_Bean.doCreate(Unknown Source)
	at no.nte.bedriftsportal.fjutt.Hark_Bean.create(Unknown Source)
	at no.nte.bedriftsportal.fjutt.Hark_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at no.nte.bedriftsportal.fjutt.Hark_ClientProxy.arc$delegate(Unknown Source)
	at no.nte.bedriftsportal.fjutt.Hark_ClientProxy.addFjuttForUser(Unknown Source)
	at no.nte.bedriftsportal.fjutt.HarkResource.addFjuttForUser(HarkResource.java:85)
	at no.nte.bedriftsportal.fjutt.HarkResource.lambda$addFjutt$4(HarkResource.java:78)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)
	at io.smallrye.mutiny.operators.uni.UniEmitOn$UniEmitOnProcessor.lambda$onItem$0(UniEmitOn.java:34)
	at io.quarkus.mongodb.impl.Wrappers.lambda$toUni$0(Wrappers.java:23)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:259)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by jmartisk** [comment]
What Quarkus version is this? Does it appear always or just intermittently?
This might have been already fixed in the main branch of Quarkus

**Comment by computerlove** [comment]
Quarkus 3.5.0, it happens on all requests. 
We'll try a nightly build.

**Comment by jmartisk** [comment]
Yeah I assume this was fixed via https://github.com/quarkusio/quarkus/pull/36623 (even though the description doesn't explicitly mention it)

**Comment by karenmnyv** [comment]
It worked with the nightly build 🎉
