### ISSUE TITLE
Enum type is not supported in directive arguments

### ISSUE THREAD

**Issue by MrHekky** [smallrye/smallrye-graphql#1978]
Hello,
when I try to use an enum type in my directive declaration like this:
```@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Directive(on = DirectiveLocation.FIELD_DEFINITION)
@Name("MyDirective")
public @interface MyDirective {

    @NonNull
    MyEnum value();

}
```
And I try to start the Quarkus application I get the error:
> 2023-11-22 19:29:10,075 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 16 more
Caused by: graphql.AssertException: wrappedType can't be null
	at graphql.Assert.assertNotNull(Assert.java:17)
	at graphql.schema.GraphQLNonNull.<init>(GraphQLNonNull.java:43)
	at graphql.schema.GraphQLNonNull.nonNull(GraphQLNonNull.java:33)
	at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLDirectiveType(Bootstrap.java:243)
	at io.smallrye.graphql.bootstrap.Bootstrap.createGraphQLDirectiveTypes(Bootstrap.java:228)
	at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:163)
	at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:120)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:52)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:42)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:32)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer.initialize(GraphQLProducer.java:27)
	at io.smallrye.graphql.cdi.producer.GraphQLProducer_ClientProxy.initialize(Unknown Source)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLRecorder.createExecutionService(SmallRyeGraphQLRecorder.java:30)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService1691419614.deploy_1(Unknown Source)
	at io.quarkus.deployment.steps.SmallRyeGraphQLProcessor$buildExecutionService1691419614.deploy(Unknown Source)
	... 17 more

I think this problem occurs because in the _Bootstrap_ class the _createGraphQLDirectiveTypes_ method (which uses _enumMap_) is invoked before _createGraphQLEnumTypes_ method. This might be a little more complicated than just switching the order of invocations, because some of the enums might use directives.
I created a small repo for reproduction purpose: https://github.com/MrHekky/graphql-enum-error-demo

**Comment by jmartisk** [comment]
@mskacelik would you like to take a look at this?

**Comment by mskacelik** [comment]
Yea, sure :-)

**Comment by mskacelik** [comment]
Created PR

>This might be a little more complicated than switching the order of invocations, because some of the enums might use directives.

`DirectivesType` created in `createGraphQLDirectiveTypes` and `DirectiveInstances` made in other `createGraphQL*` are not dependent on each other. Each creation of `DirectiveInstance` is from scratch without knowledge of `directiveTypes`. `schemaBuilder.build()` (java-graphql side) checks this dependency. So, switching these two lines of code could work. But in the PR, I mentioned some edge cases that might have problems...
