### ISSUE TITLE
NPE when the model includes java.lang.Deprecated [reproduced with WildFly Feature Pack]

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#2051]
When I use the `@Deprecated` annotation (from `java.lang`) on one of my model classes, my WildFly fails to deploy the application with these two stacktraces:

```
UT015005: Error invoking method contextDestroyed on listener class io.undertow.websockets.jsr.Bootstrap$WebSocketListener: java.lang.NullPointerException: Cannot invoke "io.undertow.websockets.jsr.ServerWebSocketContainer.close()" because "this.container" is null
	at io.undertow.websocket@2.3.12.Final//io.undertow.websockets.jsr.Bootstrap$WebSocketListener.contextDestroyed(Bootstrap.java:133)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ApplicationListeners.contextDestroyed(ApplicationListeners.java:202)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentImpl.destroy(DeploymentImpl.java:291)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$4.call(DeploymentManagerImpl.java:683)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$4.call(DeploymentManagerImpl.java:673)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl.undeploy(DeploymentManagerImpl.java:688)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:94)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

SRGQL020008: SmallRye GraphQL destroyed

MSC000001: Failed to start service jboss.deployment.unit."ROOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".undertow-deployment: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.smallrye.graphql.schema.model.DirectiveType.getName()" because "this.type" is null
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:73)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "io.smallrye.graphql.schema.model.DirectiveType.getName()" because "this.type" is null
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:257)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:88)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:70)
	... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.graphql.schema.model.DirectiveType.getName()" because "this.type" is null
	at io.smallrye.graphql//io.smallrye.graphql.schema.model.DirectiveInstance.toString(DirectiveInstance.java:41)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.FieldCreator.lambda$addDirectivesForDeprecated$0(FieldCreator.java:198)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.FieldCreator.addDirectivesForDeprecated(FieldCreator.java:196)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:110)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:69)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:68)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:36)
	at io.smallrye.graphql//io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:30)
	at io.smallrye.graphql//io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:309)
	at io.smallrye.graphql//io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:206)
	at io.smallrye.graphql//io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:138)
	at io.smallrye.graphql//io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:98)
	at io.smallrye.graphql//io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:86)
	at io.smallrye.graphql//io.smallrye.graphql.entry.http.StartupListener.contextInitialized(StartupListener.java:57)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:219)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at org.wildfly.extension.undertow@31.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1413)
	at io.undertow.servlet@2.3.12.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
	... 11 more
```

As a reproducer, just add `@Deprecated` to the `Product#name` field in https://github.com/t1/wildfly-glow-demo (it also fails without Glow) and run `mvn verify`.

**Comment by jmartisk** [comment]
Sounds very much like we need to add `java.lang.Deprecated` to the index here: https://github.com/smallrye/smallrye-graphql/blob/main/server/implementation-servlet/src/main/java/io/smallrye/graphql/entry/http/IndexInitializer.java#L99

care to give it a try?
