### ISSUE TITLE
2.8.0: TypeNotPresentException: Type io.smallrye.graphql.api.federation.FieldSet

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#2054]
After updating to 2.8.0 and updating `@Key` annotations to use `@FieldSet`, when I deploy to WildFly, I get this stacktrace, and the deployment fails:

```
MSC000001: Failed to start service jboss.deployment.unit."ROOT.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".WeldStartService: Failed to start service
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1609)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1438)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.TypeNotPresentException: Type io.smallrye.graphql.api.federation.FieldSet not present
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:441)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:241)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:227)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:349)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:282)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:4068)
	at java.base/java.lang.Class.annotationData(Class.java:4057)
	at java.base/java.lang.Class.getAnnotations(Class.java:3980)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.HotspotReflectionCache.internalGetAnnotations(HotspotReflectionCache.java:58)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.DefaultReflectionCache.lambda$new$0(DefaultReflectionCache.java:41)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:57)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:74)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.DefaultReflectionCache.getAnnotations(DefaultReflectionCache.java:77)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.DefaultReflectionCache$BackedAnnotatedTypeAnnotationsFunction.apply(DefaultReflectionCache.java:94)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.DefaultReflectionCache$BackedAnnotatedTypeAnnotationsFunction.apply(DefaultReflectionCache.java:90)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:57)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:74)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.resources.DefaultReflectionCache.getBackedAnnotatedTypeAnnotationSet(DefaultReflectionCache.java:87)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.getAnnotations(BackedAnnotatedType.java:117)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.getAnnotation(BackedAnnotatedType.java:103)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.BeanDeployer.processPriority(BeanDeployer.java:156)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.BeanDeployer.processAnnotatedTypes(BeanDeployer.java:243)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.BeanDeployment.createTypes(BeanDeployment.java:232)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:424)
	at org.jboss.weld.core@5.1.2.Final//org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:80)
	at org.jboss.as.weld@31.0.1.Final//org.jboss.as.weld.WeldStartService.start(WeldStartService.java:79)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1617)
	at org.jboss.msc@1.5.2.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1580)
	... 6 more
Caused by: java.lang.ClassNotFoundException: io.smallrye.graphql.api.federation.FieldSet from [Module "deployment.ROOT.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 42 more

07:27:39,360 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ROOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".WeldStartService" => "Failed to start service
    Caused by: java.lang.TypeNotPresentException: Type io.smallrye.graphql.api.federation.FieldSet not present
    Caused by: java.lang.ClassNotFoundException: io.smallrye.graphql.api.federation.FieldSet from [Module \"deployment.ROOT.war\" from Service Module Loader]"}}
07:27:39,360 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ROOT.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".WeldStartService" => "Failed to start service
    Caused by: java.lang.TypeNotPresentException: Type io.smallrye.graphql.api.federation.FieldSet not present
    Caused by: java.lang.ClassNotFoundException: io.smallrye.graphql.api.federation.FieldSet from [Module \"deployment.ROOT.war\" from Service Module Loader]"}}
07:27:39,361 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "ROOT.war" was rolled back with the following failure message: 
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"ROOT.war\".WeldStartService" => "Failed to start service
    Caused by: java.lang.TypeNotPresentException: Type io.smallrye.graphql.api.federation.FieldSet not present
    Caused by: java.lang.ClassNotFoundException: io.smallrye.graphql.api.federation.FieldSet from [Module \"deployment.ROOT.war\" from Service Module Loader]"}}
```

**Comment by jmartisk** [comment]
Still a problem? This sounds like you had some dependency version mismatches. Does it happen with the newly released feature pack 2.3.0.Final?

**Comment by t1** [comment]
The zip is missing from 2.3.0 feature pack

**Comment by t1** [comment]
But it works with Glow (which is a awesome project, BTW!)

**Comment by jmartisk** [comment]
I've added the overlay zip (https://github.com/wildfly-extras/wildfly-graphql-feature-pack/releases/download/2.3.0.Final/wildfly-31.0.1.Final-mp-graphql-2.3.0.Final-overlay.zip) 
I assume you had some version mismatch from using a snapshot of the feature pack that didn't yet declare proper dependency versions.

**Comment by t1** [comment]
Thanks for the zip. It works with that. The name-schema derives from the other zips, though. All other zips have the `x.0.0.Final` WF version, not `x.0.1.Final`. This breaks our current tooling.

**Comment by jmartisk** [comment]
I used the latest WF version available at the release, but you can simply build the feature pack with overriding `-Dversion.org.wildfly=31.0.0.Final` then, and find the overlay in `build/target`.
