### ISSUE TITLE
NPE on build with Quarkus 3.9.0

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#2067]
When upgrading to Quarkus 3.9.0 our application on build crash with:
```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:3.9.0:build (default) on project mittnte-api: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step io.quarkus.smallrye.graphql.client.deployment.SmallRyeGraphQLClientProcessor#buildClientModel threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.methods()" because the return value of "org.jboss.jandex.IndexView.getClassByName(org.jboss.jandex.DotName)" is null
Error:  	at io.smallrye.graphql.client.model.helper.TypeModel.hasScalarConstructor(TypeModel.java:270)
Error:  	at io.smallrye.graphql.client.model.helper.TypeModel.isScalar(TypeModel.java:260)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.recursionCheckedFields(OperationModel.java:91)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.fields(OperationModel.java:75)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.field(OperationModel.java:141)
Error:  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Error:  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
Error:  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Error:  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
Error:  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
Error:  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Error:  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Error:  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
Error:  	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
Error:  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Error:  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Error:  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
Error:  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Error:  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.recursionCheckedFields(OperationModel.java:105)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.fields(OperationModel.java:75)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.field(OperationModel.java:141)
Error:  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Error:  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
Error:  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
Error:  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
Error:  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
Error:  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Error:  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Error:  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
Error:  	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
Error:  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
Error:  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
Error:  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
Error:  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
Error:  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.recursionCheckedFields(OperationModel.java:105)
Error:  	at io.smallrye.graphql.client.model.helper.OperationModel.fields(OperationModel.java:75)
Error:  	at io.smallrye.graphql.client.model.QueryBuilder.build(QueryBuilder.java:54)
Error:  	at io.smallrye.graphql.client.model.ClientModelBuilder.lambda$generateClientModels$0(ClientModelBuilder.java:62)
Error:  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
Error:  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
Error:  	at io.smallrye.graphql.client.model.ClientModelBuilder.lambda$generateClientModels$1(ClientModelBuilder.java:61)
Error:  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Error:  	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
Error:  	at io.smallrye.graphql.client.model.ClientModelBuilder.generateClientModels(ClientModelBuilder.java:57)
Error:  	at io.smallrye.graphql.client.model.ClientModelBuilder.build(ClientModelBuilder.java:38)
Error:  	at io.quarkus.smallrye.graphql.client.deployment.SmallRyeGraphQLClientProcessor.buildClientModel(SmallRyeGraphQLClientProcessor.java:205)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
Error:  	at java.base/java.lang.Thread.run(Thread.java:840)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

Will investigate further and provide reproducer when I get the chance.

**Comment by mskacelik** [comment]
@computerlove The error message suggests that Quarkus did not index the class that you are using. Can you please provide the classes that you are using?

**Comment by computerlove** [comment]
The failing type is `java.util.Currency`.
Got it reproduces in a [minimal application](https://github.com/computerlove/npe-gql-client-quarkus-3.9.0)

**Comment by jmartisk** [comment]
Is it really a good idea to use `java.util.Currency` as part of a GraphQL domain model?
In my opinion, you would be better off having your own custom equivalent for that, then you'd have better control over it and what fields it will consist of.

Due to the recent changes where the client API is scanned at build time, it is now necessary to have all classes referenced by the client API added to the Jandex index. But most JDK classes don't get added to the index.
We could potentially try to detect such classes and add them to the index automatically before starting to build the client model, but it wouldn't be trivial. I think a better way to deal with it would be to refrain from using JDK classes as GraphQL domain classes

**Comment by jmartisk** [comment]
There's also a workaround by setting `quarkus.smallrye-graphql-client.enable-build-time-scanning=false` which I think would solve your problem, but we are planning to deprecate and remove this in the future

**Comment by khamburg-dev** [comment]
Is there anyway to see what class was not found in the index without resorting to trial and error?
