### ISSUE TITLE
java.sql.Date NoClassDefFoundError

### ISSUE THREAD

**Issue by drohne1673** [smallrye/smallrye-graphql#2156]
WF30 with smallrye featurepack 2.2.0.Final this includes SmallRye GraphQL 2.5.0. This works fine.

After upgrading to the latest Version WF32 with smallrye featurepack 2.4.0.Final this includes SmallRye GraphQL 2.9.1. the following problem occurs:

```
Caused by: java.lang.NoClassDefFoundError: java/sql/Date
2024-08-06T11:44:50.801279208Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.scalarValue(VertxTypesafeGraphQLClientProxy.java:347)
2024-08-06T11:44:50.801281846Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.value(VertxTypesafeGraphQLClientProxy.java:332)
2024-08-06T11:44:50.801284188Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.lambda$variables$20(VertxTypesafeGraphQLClientProxy.java:320)
2024-08-06T11:44:50.801286522Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2024-08-06T11:44:50.801288645Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2024-08-06T11:44:50.801290830Z 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
2024-08-06T11:44:50.801292952Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-08-06T11:44:50.801295032Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-08-06T11:44:50.801297135Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2024-08-06T11:44:50.801299398Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2024-08-06T11:44:50.801305457Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2024-08-06T11:44:50.801307852Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2024-08-06T11:44:50.801310111Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.variables(VertxTypesafeGraphQLClientProxy.java:320)
2024-08-06T11:44:50.801312862Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.request(VertxTypesafeGraphQLClientProxy.java:311)
2024-08-06T11:44:50.801315212Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.invoke(VertxTypesafeGraphQLClientProxy.java:146)
2024-08-06T11:44:50.801317554Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.invoke(VertxTypesafeGraphQLClientBuilder.java:231)
2024-08-06T11:44:50.801319891Z 	at io.smallrye.graphql.client.vertx//io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.lambda$build$0(VertxTypesafeGraphQLClientBuilder.java:191)
2024-08-06T11:44:50.801322220Z 
```
this line was added between 2.5.2 and 2.9*
```
        if (value instanceof java.sql.Date) {
            return Json.createValue(value.toString());
        }
```

we run openjdk-17-jre-headless on debian bookworm

**Comment by jmartisk** [comment]
I think we need to declare that the client module now depends on the `javax.sql.api` module. 
As a workaround, could you try manually changing your wildfly's `modules/system/layers/base/io/smallrye/graphql/client/vertx/main/module.xml` and add 
```
<module name="javax.sql.api"/>
```

into its `<dependencies>` section to see if that fixes it?

**Comment by drohne1673** [comment]
![Screenshot_20240806_150605](https://github.com/user-attachments/assets/9a3a8262-f3c0-42b5-b2a2-f230c826439b)

this indeed fixed the issue. thank you very much for the fast response :+1:

**Comment by t1** [comment]
Hmmm... maybe it would still be better to make the client not rely on the `javax.sql.api` module. I might want to build a lean WildFly with Glow without any SQL.

**Comment by drohne1673** [comment]
any idea when a fix will be available? otherwise i might need to lookup how i can create an overlay so i can actually install this version

**Comment by jmartisk** [comment]
Sorry @drohne1673, I'd somehow dropped this from my radar.. I've submitted https://github.com/wildfly-extras/wildfly-graphql-feature-pack/pull/179 with the quick fix of just adding the dependency. I'll put out a micro release after this. We may consider removing the compile time dependency, as @t1 suggested, in the future.
