### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-graphql#2230]
With this code:

```java
@GraphQLApi
public class HelloGraphQLResource {

    @Query
    @Description("Say hello")
    public CompletionStage<List<Message>> sayHello(@DefaultValue("World") String name) {
        return CompletableFuture.supplyAsync(() -> List.of(new Message("Hello " + name)));
        
    }
    
    public List<String> bla(@Source List<Message> message) throws MyException{
        throw new MyException("Some checked exception 3");
    }
}
```

and this query:

```graphql
{
  sayHello(name:"Foo"){
    name
    bla
  }
}
```

I get the following error:

```
LogManager error of type FORMAT_FAILURE: Formatting error
java.util.UnknownFormatConversionException: Conversion = '$'
        at org.jboss.logmanager.formatters.Printf.unknownFormat(Printf.java:1111)
        at org.jboss.logmanager.formatters.Printf.unknownFormat(Printf.java:1107)
        at org.jboss.logmanager.formatters.Printf.formatDirect(Printf.java:602)
        at org.jboss.logmanager.formatters.ColorPrintf.formatDirect(ColorPrintf.java:43)
        at org.jboss.logmanager.formatters.Printf.format(Printf.java:95)
        at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:131)
        at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)
        at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)
        at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:152)
        at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)
        at org.jboss.logmanager.ExtFormatter$Delegating.format(ExtFormatter.java:196)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:52)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:485)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:420)
        at io.quarkus.runtime.logging.LoggingSetupRecorder$7.doPublish(LoggingSetupRecorder.java:623)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:125)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:1089)
        at org.jboss.logmanager.Logger.log(Logger.java:1052)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.logf(Logger.java:2447)
        at io.smallrye.graphql.SmallRyeGraphQLServerLogging_$logger.dataFetchingError(SmallRyeGraphQLServerLogging_$logger.java:101)
        at io.smallrye.graphql.execution.error.ExceptionHandler.handleException(ExceptionHandler.java:33)
        at graphql.execution.ExecutionStrategy.asyncHandleException(ExecutionStrategy.java:604)
        at graphql.execution.ExecutionStrategy.handleFetchingException(ExecutionStrategy.java:592)
        at graphql.execution.ExecutionStrategy.lambda$fetchField$11(ExecutionStrategy.java:508)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onFailure(UniOnItemOrFailureConsume.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:60)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$3(DataLoaderHelper.java:280)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:604)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
LogManager error of type WRITE_FAILURE: Nested handler publication threw an exception
java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
        at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2911)
        at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2982)
        at java.base/java.util.Formatter.parse(Formatter.java:2849)
        at java.base/java.util.Formatter.format(Formatter.java:2774)
        at java.base/java.util.Formatter.format(Formatter.java:2728)
        at java.base/java.lang.String.format(String.java:4390)
        at org.jboss.logmanager.ExtLogRecord.getFormattedMessage(ExtLogRecord.java:512)
        at io.quarkus.devui.runtime.logstream.JsonFormatter.toJsonObject(JsonFormatter.java:30)
        at io.quarkus.devui.runtime.logstream.MutinyLogHandler.doPublish(MutinyLogHandler.java:39)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:125)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:1089)
        at org.jboss.logmanager.Logger.log(Logger.java:1052)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.logf(Logger.java:2447)
        at io.smallrye.graphql.SmallRyeGraphQLServerLogging_$logger.dataFetchingError(SmallRyeGraphQLServerLogging_$logger.java:101)
        at io.smallrye.graphql.execution.error.ExceptionHandler.handleException(ExceptionHandler.java:33)
        at graphql.execution.ExecutionStrategy.asyncHandleException(ExecutionStrategy.java:604)
        at graphql.execution.ExecutionStrategy.handleFetchingException(ExecutionStrategy.java:592)
        at graphql.execution.ExecutionStrategy.lambda$fetchField$11(ExecutionStrategy.java:508)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onFailure(UniOnItemOrFailureConsume.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:60)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$3(DataLoaderHelper.java:280)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:604)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by phillip-kruger** [comment]
This will be fixed with https://github.com/jboss-logging/jboss-logmanager/pull/493
Thanks @gsmet :)

**Comment by gsmet** [comment]
@phillip-kruger I'm not entirely sure this will get fixed by the Log Manager update as I was using a log method with no formatting at all when having the issue and you're using `logf`. So probably a good idea to check the issue has actually been fixed in your case.

**Comment by phillip-kruger** [comment]
@gsmet yes this issue was not fixed with https://github.com/jboss-logging/jboss-logmanager/pull/493

@dmlloyd can you help ?  I include I reproducer here: 
[logging-error-graphql.zip](https://github.com/user-attachments/files/17953035/logging-error-graphql.zip)


After starting the app (dev mode is fine) run the following query:

```
curl -X POST \
  http://localhost:8080/graphql \
  -H "Content-Type: application/json" \
  -d '{"query":"{ sayHello(name:\"Foo\") { name bla } }"}'
```

This should give you:

```
LogManager error of type FORMAT_FAILURE: Formatting error
java.util.UnknownFormatConversionException: Conversion = '$'
        at org.jboss.logmanager.formatters.Printf.unknownFormat(Printf.java:1111)
        at org.jboss.logmanager.formatters.Printf.unknownFormat(Printf.java:1107)
        at org.jboss.logmanager.formatters.Printf.formatDirect(Printf.java:602)
        at org.jboss.logmanager.formatters.ColorPrintf.formatDirect(ColorPrintf.java:43)
        at org.jboss.logmanager.formatters.Printf.format(Printf.java:95)
        at org.jboss.logmanager.formatters.ColorPatternFormatter.formatMessage(ColorPatternFormatter.java:131)
        at org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:832)
        at org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:227)
        at org.jboss.logmanager.formatters.ColorPatternFormatter$ColorStep.render(ColorPatternFormatter.java:152)
        at org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:90)
        at org.jboss.logmanager.ExtFormatter$Delegating.format(ExtFormatter.java:196)
        at org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:58)
        at org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:54)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:485)
        at io.quarkus.deployment.logging.LoggingResourceProcessor$2.accept(LoggingResourceProcessor.java:420)
        at io.quarkus.runtime.logging.LoggingSetupRecorder$7.doPublish(LoggingSetupRecorder.java:623)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:125)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:921)
        at org.jboss.logmanager.Logger.log(Logger.java:884)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.logf(Logger.java:2447)
        at io.smallrye.graphql.SmallRyeGraphQLServerLogging_$logger.dataFetchingError(SmallRyeGraphQLServerLogging_$logger.java:101)
        at io.smallrye.graphql.execution.error.ExceptionHandler.handleException(ExceptionHandler.java:33)
        at graphql.execution.ExecutionStrategy.asyncHandleException(ExecutionStrategy.java:604)
        at graphql.execution.ExecutionStrategy.handleFetchingException(ExecutionStrategy.java:592)
        at graphql.execution.ExecutionStrategy.lambda$fetchField$11(ExecutionStrategy.java:508)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onFailure(UniOnItemOrFailureConsume.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:60)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$3(DataLoaderHelper.java:280)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:604)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
LogManager error of type WRITE_FAILURE: Nested handler publication threw an exception
java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
        at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2911)
        at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2982)
        at java.base/java.util.Formatter.parse(Formatter.java:2849)
        at java.base/java.util.Formatter.format(Formatter.java:2774)
        at java.base/java.util.Formatter.format(Formatter.java:2728)
        at java.base/java.lang.String.format(String.java:4390)
        at org.jboss.logmanager.ExtFormatter.formatMessagePrintf(ExtFormatter.java:144)
        at org.jboss.logmanager.ExtFormatter.formatMessage(ExtFormatter.java:91)
        at io.quarkus.devui.runtime.logstream.JsonFormatter.toJsonObject(JsonFormatter.java:30)
        at io.quarkus.devui.runtime.logstream.MutinyLogHandler.doPublish(MutinyLogHandler.java:39)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.ExtHandler.publishToNestedHandlers(ExtHandler.java:125)
        at io.quarkus.bootstrap.logging.QuarkusDelayedHandler.doPublish(QuarkusDelayedHandler.java:81)
        at org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:88)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:438)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:480)
        at org.jboss.logmanager.Logger.logRaw(Logger.java:921)
        at org.jboss.logmanager.Logger.log(Logger.java:884)
        at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:56)
        at org.jboss.logging.Logger.logf(Logger.java:2447)
        at io.smallrye.graphql.SmallRyeGraphQLServerLogging_$logger.dataFetchingError(SmallRyeGraphQLServerLogging_$logger.java:101)
        at io.smallrye.graphql.execution.error.ExceptionHandler.handleException(ExceptionHandler.java:33)
        at graphql.execution.ExecutionStrategy.asyncHandleException(ExecutionStrategy.java:604)
        at graphql.execution.ExecutionStrategy.handleFetchingException(ExecutionStrategy.java:592)
        at graphql.execution.ExecutionStrategy.lambda$fetchField$11(ExecutionStrategy.java:508)
        at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onFailure(UniOnItemOrFailureConsume.java:46)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:60)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$3(DataLoaderHelper.java:280)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:604)
        at io.vertx.core.impl.future.FutureImpl$4.onFailure(FutureImpl.java:188)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:81)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by gsmet** [comment]
I have some time before calling it a day, let me try to diagnose this a bit more precisely.

**Comment by gsmet** [comment]
^ has been merged.

**Comment by phillip-kruger** [comment]
Thanks @gsmet !
