### ISSUE TITLE
Validation: @NotNull in Optional throws NPE

### ISSUE THREAD

**Issue by RoMiRoSSaN** [smallrye/smallrye-graphql#2231]
Hi. I found a very strange case, which is probably an error in using validations.

```java
@GraphQLApi
public class HelloGraphQLResource {
    @Query
    public String request(@Valid Model model) {
        return String.valueOf(model);
    }

    @Query
    public String request2(@Valid Model2 model) {
        return String.valueOf(model);
    }
}

public record Model(Optional<@NotNull @Size(min = 5) String> value) {
}

@Data
public class Model2 {
    private Optional<@NotNull @Size(min = 5) String> value;
}
```

Hibernate validator allows you to set constraints inside Optional.

Here the following schema will be generated and the following queries can be resolved

```
type Query {
  sayHello(model: ModelInput): String
}

input ModelInput {
  value: String
}

input Model2Input {
  value: String
}
```

```
{
  i1: request(model:{value: "asdasd"})
  i2: request(model:{value: null})
  i3: request(model:{})
  i4: request

  j1: request2(model:{value: "asdasd"})
  j2: request2(model:{value: null})
  j3: request2(model:{})
  j4: request2
}
```

Queries i2 and i3 should throw a message that the field cannot be null, but in fact in io.smallrye.graphql.validation.BeanValidationError.getViolationAttributes npe comes out because the value of violation.getInvalidValue() is null. Map does the check inside Objects.requireNonNull.

```
ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-1) Mutiny had to drop the following exception: java.lang.NullPointerException
->	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
->	at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1193)
->	at java.base/java.util.Map.of(Map.java:1431)
->	at io.smallrye.graphql.validation.BeanValidationError.getViolationAttributes(BeanValidationError.java:65)
	.........
	at io.smallrye.graphql.validation.BeanValidationError.getExtensions(BeanValidationError.java:61)
	at graphql.GraphqlErrorHelper.toSpecification(GraphqlErrorHelper.java:30)
	at graphql.GraphQLError.toSpecification(GraphQLError.java:63)
	at io.smallrye.graphql.execution.error.ExecutionErrorsService.toJsonError(ExecutionErrorsService.java:53)
	at io.smallrye.graphql.execution.error.ExecutionErrorsService.toJsonErrors(ExecutionErrorsService.java:47)
	at io.smallrye.graphql.execution.ExecutionResponse.addErrorsToResponse(ExecutionResponse.java:94)
	at io.smallrye.graphql.execution.ExecutionResponse.getExecutionResultAsJsonObject(ExecutionResponse.java:78)
	at io.smallrye.graphql.execution.ExecutionService.logOutput(ExecutionService.java:416)
	at io.smallrye.graphql.execution.ExecutionService.notifyAndWrite(ExecutionService.java:281)
	at io.smallrye.graphql.execution.ExecutionService.lambda$writeAsync$1(ExecutionService.java:251)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	.........
	at graphql.execution.AbstractAsyncExecutionStrategy.lambda$handleResults$0(AbstractAsyncExecutionStrategy.java:37)
	........
	at graphql.execution.AsyncExecutionStrategy.lambda$execute$0(AsyncExecutionStrategy.java:77)
	.....
	at graphql.execution.Async$Many.lambda$await$0(Async.java:226)
	......
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureConsume$UniOnItemOrFailureConsumeProcessor.onItem(UniOnItemOrFailureConsume.java:37)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
```

As a result, no response will ever be received by the client.

If you use a class instead of a record, then query j3 will work, but j2 still thrown NPE. 

The difference is that in request 3, if a record is used, Optional.empty is generated, even if the field was not sent. If a class - then if the field is not actually passed in the request, then it will be null in the object.
Is this difference between record and class normal?

Do you think my case is a bug or not correct and I shouldn’t do this?

**Comment by jmartisk** [comment]
I think this was fixed by this commit: https://github.com/smallrye/smallrye-graphql/commit/6f9c9c6b5dbec0338f7ba55b6c1a09e10b513ed3 but we don't have a released version with it yet

**Comment by RoMiRoSSaN** [comment]
So fast) 
Cool, I'll wait) there was an isolated case, we'll use a different way. 
What about the fact that record and class create different objects?

**Comment by jmartisk** [comment]
I think that's because of how Yasson (the JSON-B implementation that we use to deserialize JSON objects) works - for records, it calls the canonical constructor of the record, so it has to actually provide a value for the field. For regular classes, it uses the no-arg constructor and setters, so if there's no value to set for a field, it won't call the setter.

**Comment by RoMiRoSSaN** [comment]
OK. I understand. Thank you. I'll see how Yasson works. then I'll close this thread
