### ISSUE TITLE
Support Kotlin 2.1

### ISSUE THREAD

**Issue by panphg** [smallrye/smallrye-graphql#2233]
We have a Quarkus app written in Kotlin that provides a GraphQL API. We recently tried to update the app to Kotlin 2.1 but ran into the following error when building with Gradle:
```
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.IllegalArgumentException: Provided Metadata instance has version 2.1.0, while maximum supported version is 2.0.0. To support newer versions, update the kotlinx-metadata-jvm library.
                at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.throwIfNotCompatible$kotlinx_metadata_jvm(KotlinClassMetadata.kt:609)
                at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.checkMetadataVersionForRead(KotlinClassMetadata.kt:600)
                at kotlinx.metadata.jvm.KotlinClassMetadata$Companion.read(KotlinClassMetadata.kt:579)
                at kotlinx.metadata.jvm.KotlinClassMetadata.read(KotlinClassMetadata.kt)
                at io.smallrye.graphql.schema.creator.OperationCreator.toKotlinClassMetadata(OperationCreator.java:264)
                at io.smallrye.graphql.schema.creator.OperationCreator.checkWrappedTypeKotlinNullability(OperationCreator.java:126)
                at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:112)
                at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:369)
                at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:150)
                at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:104)
                at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:324)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
                at java.base/java.lang.reflect.Method.invoke(Method.java:580)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
                at java.base/java.lang.Thread.run(Thread.java:1583)
                at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

It looks like the Kotlin metadata changed in 2.1 and you need to update the dependency `kotlinx-metadata-jvm` to `kotlin-metadata-jvm:2.1.0`. 
Note: they renamed the dependency to `kotlin-metadata-jvm` (no x after kotlin).

**Comment by jmartisk** [comment]
Oh, thanks for letting me know about the update. I'd completely missed that and now we've just upgraded to kotlinx-metadata-jvm:0.9.0. I'll try to update to the new artifact

**Comment by jmartisk** [comment]
Fixed via https://github.com/smallrye/smallrye-graphql/pull/2239
