### ISSUE TITLE
Support java.util.Date in queries from smallrye-graphql-client

### ISSUE THREAD

**Issue by gastaldi** [smallrye/smallrye-graphql#337]
I am using this library to fetch data from GitHub and I noticed that some types are not assembled correctly. This is what I have so far:  

```java 
@GraphQlClientApi(endpoint = "https://api.github.com/graphql")
@AuthorizationHeader(confPrefix = "github", type = AuthorizationHeader.Type.BEARER)
public interface GitHub {

    @Query("repository")
    Repository repository(String owner, String name);
}
```

This is the `Repository` class: 

```java
public class Repository {
    public String id;
    public java.util.Date createdAt;
}
```

This is my test: 

```java
    @Test
    void test() {
        final GitHub github = GraphQlClientBuilder.newBuilder().build(GitHub.class);
        System.out.println(github.repository("gastaldi", "backport-repo"));
    }
```

And this is the error I get: 

```java
io.smallrye.graphql.client.typesafe.api.GraphQlClientException: errors from service: [{"message":"Parse error on \"}\" (RCURLY) at [1, 77]","locations":[{"line":1,"column":77}]}]:
  {"query":"query { repository(owner: \"gastaldi\", name: \"backport-repo\") {id createdAt {}} }"}

	at io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.readResponse(GraphQlClientProxy.java:128)
	at io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.fromJson(GraphQlClientProxy.java:120)
	at io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.invoke(GraphQlClientProxy.java:52)
	at io.smallrye.graphql.client.typesafe.impl.GraphQlClientBuilderImpl.lambda$build$0(GraphQlClientBuilderImpl.java:45)
	at com.sun.proxy.$Proxy18.repository(Unknown Source)
	at io.quarkus.backports.GraphQLTest.test(GraphQLTest.java:12)
```

**Comment by phillip-kruger** [comment]
Thanks for this. We support java.util.Date on the server, so it would make sense to do the same on the client.
@t1 - any thoughts ?

**Comment by ybroeker** [comment]
If I see this correctly, the error is in the query. The bracket at position 77 (and 76) in the query is incorrect.

**Comment by t1** [comment]
I'm taking a look
