### ISSUE TITLE
Schema generation fails if generic field resolves type from enclosing class

### ISSUE THREAD

**Issue by velias** [smallrye/smallrye-graphql#423]
Follow up on generic support added in #281.
This structure in class:

```
public class PagedResultConnection<V> {

    @NonNull
    protected List<PagedResultEdge<V>> edges = new ArrayList<>();
...
```
used this way in the GraphQL API:

```
@Query
public PagedResultConnection<String> getGenerics() { 
...
```

results in:

```
io.smallrye.graphql.schema.SchemaBuilderException: Don't know what to do with [V] of kind [TYPE_VARIABLE] as parent object reference is missing or incomplete
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:299)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:234)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReference(ReferenceCreator.java:203)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:291)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:234)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:265)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForPojoField(ReferenceCreator.java:140)
	at io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:114)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:101)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:69)
	at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:40)
	at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:180)
	at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:113)
	at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:94)
	at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:65)
	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:156)
```

**Comment by velias** [comment]
I'm working on this issue and will provide PR to resolve it

**Comment by velias** [comment]
It fails even in case when subclass is created to resolve generic and it is used in the API handler

```
public class PagedResultConnectionResolvedToString extends PagedResultConnection<String> {

}
```

**Comment by phillip-kruger** [comment]
@velias - can we close this issue ?

**Comment by velias** [comment]
Yes please, close it
