### ISSUE TITLE
Batch Resolvers throws NullPointerException

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#464]
You [mentioned ](https://github.com/smallrye/smallrye-graphql/issues/445#issuecomment-703542343) that Batch ([like here](https://github.com/smallrye/smallrye-graphql/pull/397)) should work with Quarkus 1.9 and GraphQL 1.0.12 but it does not.

I tried using io.quarkus:quarkus-smallrye-graphql:1.9.0.CR1 with io.smallrye:smallrye-graphql-cdi:1.0.12 inside.

**I am getting following Stackstrace:**

```
2020-10-12 11:02:29,655 ERROR [io.sma.graphql] (ForkJoinPool.commonPool-worker-29) SRGQL012000: Data Fetching Error: java.util.concurrent.CompletionException: java.lang.
NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
        at org.dataloader.DataLoaderHelper.dispatchQueueBatch(DataLoaderHelper.java:206)
        at org.dataloader.DataLoaderHelper.dispatch(DataLoaderHelper.java:170)
        at org.dataloader.DataLoader.dispatch(DataLoader.java:473)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.dataloader.DataLoaderRegistry.dispatchAll(DataLoaderRegistry.java:114)
        at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach.dispatch(FieldLevelTrackingApproach.java:292)
        at graphql.execution.instrumentation.dataloader.FieldLevelTrackingApproach$1.onFieldValuesInfo(FieldLevelTrackingApproach.java:160)
        at graphql.execution.instrumentation.ChainedInstrumentation$ChainedExecutionStrategyInstrumentationContext.lambda$onFieldValuesInfo$2(ChainedInstrumentation.java
:293)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at graphql.execution.instrumentation.ChainedInstrumentation$ChainedExecutionStrategyInstrumentationContext.onFieldValuesInfo(ChainedInstrumentation.java:293)
        at graphql.execution.AsyncExecutionStrategy.lambda$execute$1(AsyncExecutionStrategy.java:88)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at graphql.execution.Async.lambda$each$0(Async.java:40)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
        at io.smallrye.graphql.execution.batchloader.SourceBatchLoader.doSourceCall(SourceBatchLoader.java:77)
        at io.smallrye.graphql.execution.batchloader.SourceBatchLoader.access$000(SourceBatchLoader.java:27)
        at io.smallrye.graphql.execution.batchloader.SourceBatchLoader$1.run(SourceBatchLoader.java:63)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.smallrye.graphql.execution.batchloader.SourceBatchLoader.invokePrivileged(SourceBatchLoader.java:56)
        at io.smallrye.graphql.execution.batchloader.SourceBatchLoader.load(SourceBatchLoader.java:47)
        at org.dataloader.DataLoaderHelper.invokeListBatchLoader(DataLoaderHelper.java:306)
        at org.dataloader.DataLoaderHelper.invokeLoader(DataLoaderHelper.java:294)
        at org.dataloader.DataLoaderHelper.dispatchQueueBatch(DataLoaderHelper.java:203)
        ... 26 more
```

my definition:
```
@GraphQLApi
public class PersonResource {
{

    @Query
    public CompletableFuture<Person> getPerson(long id) throws InterruptedException {
        return CompletableFuture.supplyAsync(() -> backendService.getPerson(id));
    }

   public CompletableFuture<List<Adress>> getAdresses(@Source Person p) throws InterruptedException{ 
        return CompletableFuture.supplyAsync(() -> backendService.getAdressesForPerson(p.id));
    }

   public  CompletableFuture<List<DetailAdress>> getDetailAdresses(@Source List<Adress> addresses) throws InterruptedException { 
        return ...; // load for ever adress a detailadress (probably also async)
    }

}
```

**Comment by phillip-kruger** [comment]
Hi @michaelsonnleitner - Do you have small project that recreate this that I can look at ? That will help a lot :)

**Comment by phillip-kruger** [comment]
@eamelink might also be interested in this.

**Comment by michaelsonnleitner** [comment]
here my sample: 
https://github.com/michaelsonnleitner/sample-async-graphql

```
query person
{
  person(id:1)
  {
    firstname
    adresses
    {
      detailAdresses
      {
        stuff
      }
    }
  }
}
```

output:
```
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 8,
          "column": 7
        }
      ],
      "path": [
        "person",
        "adresses",
        0,
        "detailAdresses"
      ],
      "extensions": {
        "exception": "java.util.concurrent.CompletionException",
        "classification": "DataFetchingException",
        "code": "completion"
      }
    }
  ],
  "data": {
    "person": {
      "firstname": "Kruger",
      "adresses": [
        {
          "detailAdresses": null
        }
      ]
    }
  }
}
```

**Comment by phillip-kruger** [comment]
Ok, this is the context. It happens when there is a future on a future. I'll look at this.

**Comment by michaelsonnleitner** [comment]
i did not want to close it

**Comment by phillip-kruger** [comment]
This should be fixed in the next version. Please reopen if you still get this issue in Quarkus 1.10.0
