### ISSUE TITLE
Serialization fails at runtime for generic class which implements generic interface

### ISSUE THREAD

**Issue by velias** [smallrye/smallrye-graphql#472]
Serialization sometimes fails at runtime for generic class which implements generic interface if it is resolved with more types. Error is like:

```
Can't resolve '/pagedResultResolvedToInt/edges[1]'. Abstract type 'IPagedResultEdge_Int' must resolve to an Object type at runtime for field '[IPagedResultEdge_Int].edges'. Runtime Object type 'PagedResultEdge_String' is not a possible type for 'IPagedResultEdge_Int'.: graphql.execution.UnresolvedTypeException: Runtime Object type 'PagedResultEdge_String' is not a possible type for 'IPagedResultEdge_Int'.
	at graphql.execution.ResolveType.resolveTypeForInterface(ResolveType.java:55)
	at graphql.execution.ResolveType.resolveType(ResolveType.java:27)
	at graphql.execution.ExecutionStrategy.resolveType(ExecutionStrategy.java:689)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:442)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:538)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:490)
```

Problem looks to be in `io.smallrye.graphql.execution.resolver.InterfaceResolver` or `io.smallrye.graphql.execution.resolver.InterfaceOutputRegistry` which looks to be based on java class names only so generics are not reflected there correctly.

Follow up on generic support added in #281.

**Comment by velias** [comment]
@phillip-kruger working on this, hope I'll be able to crate PR soon

**Comment by phillip-kruger** [comment]
Great!! Thanks @velias

**Comment by velias** [comment]
patched in PR #474 with relevant test

**Comment by phillip-kruger** [comment]
@velias - we can close this right ?

**Comment by velias** [comment]
Yes please, thanks
