### ISSUE TITLE
Integrate smallrye-graphql in JBoss EAP 7.2 without Microprofile

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#475]
Is it somehow possible to integrate this implementation into a **none** Eclipse Microprofile Container (eg. JBoss EAP 7.2.3)

I tried to add both dependenies to my pom.xml, but I got some clazz not found exception regarding MP tracing.

```
<dependency>
	<groupId>io.smallrye</groupId>
	<artifactId>smallrye-graphql</artifactId>
	<version>1.0.14</version>
</dependency>
<dependency>
	<groupId>io.smallrye</groupId>
	<artifactId>smallrye-graphql-servlet</artifactId>
	<version>1.0.14</version>
</dependency>
```

What do I have to?

**Comment by phillip-kruger** [comment]
You should only need the servlet dependency.

Can you post the full exception ?

**Comment by phillip-kruger** [comment]
It should work, we do this with out tests. Although we have MP Config.... So you might need to bootstrap this yourself....

**Comment by michaelsonnleitner** [comment]
**this from Metrics:**
```
12:04:37,748 WARN  [org.jboss.modules.define] (Weld Thread Pool -- 6) Failed to define class io.smallrye.graphql.cdi.metrics.MetricsService$VendorType in Module "deployment.b-war-1.16.0-SNAPSHOT.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link io/smallrye/graphql/cdi/metrics/MetricsService$VendorType (Module "deployment.b-war-1.16.0-SNAPSHOT.war" from Service Module Loader): org/eclipse/microprofile/metrics/annotation/RegistryType
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:833)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:519)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.weld.WeldModuleResourceLoader.classForName(WeldModuleResourceLoader.java:68)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadClass(AnnotatedTypeLoader.java:82)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:62)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:108)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:55)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:52)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)

```

**this from Config**
``` 
12:04:49,067 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-5) MSC000001: Failed to start service jboss.deployment.unit."b-war-1.16.0-SNAPSHOT.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."b-war-1.16.0-SNAPSHOT.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1730)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type GraphQLConfig with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject io.smallrye.graphql.cdi.producer.GraphQLProducer.graphQLConfig
  at io.smallrye.graphql.cdi.producer.GraphQLProducer.graphQLConfig(GraphQLProducer.java:0)
WELD-001474: Class io.smallrye.graphql.cdi.config.GraphQLConfig is on the classpath, but was ignored because a class it references was not found: org.eclipse.microprofile.config.Config from [Module "deployment.b-war-1.16.0-SNAPSHOT.war" from Service Module Loader].

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
```

**Comment by michaelsonnleitner** [comment]
> It should work, we do this with out tests. Although we have MP Config.... So you might need to bootstrap this yourself....

where? do you have a link to a repo?

**Comment by phillip-kruger** [comment]
Ok, so our CDI module assumes MP is available (that is why you get the errors).

To get this working on Non MP, you basically need to do what the CDI module and Servlet module does. Theoretically, you should actually be able to get with working on Spring.

### This is what the CDI module does:

1) Inject the Config using MP Config.

So you need to create your own Config (implements `io.smallrye.graphql.bootstrap.Config`) that supply the config values. With JBoss you can possibly use JNDI or just hardcode 

2) For **Metrics** and **Tracing**, you can just ignore those, at least for now. This sets up MP Metrics and MP Tracing, that JBoss does not have.

3) For **Events** you should be able to use something similar as in the CDI module. Events is a SPI (so also see the META-INF/services) that translate the smallrye events to CDI events. If you do not need this (highly likely that you do not use this)  you can just ignore.

4) For **Validation**, you should be able to use something similar as in the CDI module. Validation is a SPI (so also see the META-INF/services) that hooks in Bean Validation. If you are not using Bean validation, you can just ignore.

5) You are going to need a lookup service, but if you have CDI, you should be able to use the one the CDI Module. (https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/CdiLookupService.java). This is also a SPI, so also see the file in META-INF. This basically do the lookup of the `@GraphQLAPI` Class. So if you want to use Spring you should be able to write something that look up a Spring bean. (Theoretically)

6) You also need something that produce the relevant beans. Again you should be able to use something like https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation-cdi/src/main/java/io/smallrye/graphql/cdi/producer/GraphQLProducer.java

**What the Servlet Module does**
You should be able to use our Servlet module, except you need to use your own CDI module. You also have the options to use something else, like what the Quarkus Extension does, where we use Vert.x.

Hope that helps.

If you have a project somewhere available that I can look at I can assist.

**Comment by jmartisk** [comment]
Have you tried the GraphQL feature pack for WildFly? See https://github.com/wildfly-extras/wildfly-graphql-feature-pack
I'm not completely sure it will work with EAP 7.2, I test with WildFly 20+ right now, but it could work, perhaps with some caveats
Let me know if you need help installing that. It would be cool if we managed to get it working with EAP and documented the potential EAP-specific stuff

**Comment by michaelsonnleitner** [comment]
I tried EAP 7.3.2 with [JBoss EAP XP 1.0.0](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/using_eclipse_microprofile_with_jboss_eap_xp_1.0.0/index) and I added smallrye-graphql servlet dependency and that works for me. 

```
        <dependency>
            <groupId>io.smallrye</groupId>
            <artifactId>smallrye-graphql-servlet</artifactId>
            <version>1.0.14</version>
        </dependency>
```
