### ISSUE TITLE
Support any map type.

### ISSUE THREAD

**Issue by patope** [smallrye/smallrye-graphql#493]
Test case below 

```
class ReferenceCreatorTest {

    public static class MapImpl extends AbstractMap<String,String> implements Map<String,String> {
        @Override
        public Set<Entry<String, String>> entrySet() {
            return null;
        }
    }

    @Test
    public void test() throws Exception {
        try {
            ReferenceCreator referenceCreator = new ReferenceCreator(TypeAutoNameStrategy.Full);
            // Modified IndexCreator to accept variable number of arguments
            Index index = IndexCreator.index(Map.class, MapImpl.class);
            ScanningContext.register(index);
            Reference reference = referenceCreator.createReference(Direction.OUT, index.getClassByName(DotName.createSimple(Map.class.getName())));
            // reference should be?
        } finally {
            ScanningContext.remove();
        }
    }
}
```

throws exception
```
java.lang.IllegalArgumentException: Not a type variable!

	at org.jboss.jandex.Type.asTypeVariable(Type.java:241)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReference(ReferenceCreator.java:203)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReference(ReferenceCreator.java:161)
	at io.smallrye.graphql.schema.creator.ReferenceCreatorTest.test(ReferenceCreatorTest.java:31)
       ...
```

I have panache jpa model that triggers this issue. `io.smallrye.config.ConfigSourceMap` is direct implementer of Map.

**Comment by phillip-kruger** [comment]
Thanks for this. We will need to see how we can accommodate this.
