### ISSUE TITLE
Regression: type Instant not found in schema

### ISSUE THREAD

**Issue by patope** [smallrye/smallrye-graphql#666]
After upgrading quarkus-1.12.1.Final. I'm getting this error...

```
Caused by: graphql.AssertException: type Instant not found in schema
	at graphql.Assert.assertNotNull(Assert.java:17)
	at graphql.schema.GraphQLTypeResolvingVisitor.handleTypeReference(GraphQLTypeResolvingVisitor.java:49)
	at graphql.schema.GraphQLTypeResolvingVisitor.visitGraphQLTypeReference(GraphQLTypeResolvingVisitor.java:44)
	at graphql.schema.GraphQLTypeReference.accept(GraphQLTypeReference.java:55)
	at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:72)
	at graphql.util.Traverser.traverse(Traverser.java:144)
	at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:59)
```

```
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Input;
import org.eclipse.microprofile.graphql.Query;

import java.time.Instant;

@GraphQLApi
public class TestGQL {

    @Input
    public static class Data {
        String id;
        Instant now;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public Instant getNow() {
            return now;
        }

        public void setNow(Instant now) {
            this.now = now;
        }
    };

    @Query
    public Data query() {
        Data data = new Data();
        data.now = Instant.now();
        data.id = "";
        return data;
    }
}
```

**Comment by phillip-kruger** [comment]
Thanks @patope , I'll have a look a.s.a.p

**Comment by patope** [comment]
with quarkus 1.12.0. Graphql gives lot of warnings 
```
[WARNING] [io.smallrye.graphql.schema.creator.ReferenceCreator] Class [java.time.Instant] in not indexed in Jandex. Can not scan Object Type, defaulting to String Scalar
```
IMO this is fine and warning is not necessary. Maybe debug or trace would be more suitable. All java.time.* can be String scalars.

**Comment by phillip-kruger** [comment]
Those should actually be picked up by DateTime. I'll have a look a.s.a.p.

**Comment by shinji62** [comment]
WE have the same issue there please :) @phillip-kruger

**Comment by phillip-kruger** [comment]
Ok, I have a PR open for this. Just to explain what happened here.
`java.time.Instant` was never supported, but there was a fallback in place that treat all unknown's a String. 
(that has been removed, as it can hide some issues)

This worked, even though this should really be a DateTime, so the PR does a proper fix by treating Instant as a DateTime.

Hope that will solve your issue.
