### ISSUE TITLE
@Query annotations in @GraphQlClientApi cause errors when mixed with @Mutation annotations

### ISSUE THREAD

**Issue by WhiteCat22** [smallrye/smallrye-graphql#714]
In my `@GraphQlClientApi` class, you don't have to annotate your `@Query methods`. I do have to annotate my `@Mutation` methods otherwise the client will attempt to query, which fails validation. , Great, `@Query` is the default.

However, when I want to explicitly annotate a mix of `@Query` and `@Mutation` methods, I get a `java.lang.IllegalStateException: client is closed` jaxrs failure when invoking my `@Mutation` and the following error when I invoke my `@Query`:

```
Stack Dump = io.smallrye.graphql.client.typesafe.api.GraphQlClientException: compile with -parameters to add the parameter names to the class file
at io.smallrye.graphql.client.typesafe.impl.reflection.ParameterInfo.getName(ParameterInfo.java:40)
at io.smallrye.graphql.client.typesafe.impl.RequestBuilder.appendParam(RequestBuilder.java:38)
at io.smallrye.graphql.client.typesafe.impl.RequestBuilder.build(RequestBuilder.java:30)
at io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.request(GraphQlClientProxy.java:60)
at io.smallrye.graphql.client.typesafe.impl.GraphQlClientProxy.invoke(GraphQlClientProxy.java:46)
at io.smallrye.graphql.client.typesafe.impl.GraphQlClientBuilderImpl.lambda$build$0(GraphQlClientBuilderImpl.java:47)
at io.smallrye.graphql.client.typesafe.impl.GraphQlClientBuilderImpl$$Lambda$383.0000000008854220.invoke(Unknown Source)
...
```

So, currently I MUST explicitly annotate my `@Mutation` methods without explicitly annotating my `@Query` methods

Example:
```
@GraphQlClientApi
public interface GraphQLClient {

//	  @Query
    public List<Car> getCars();
	
//    @Query
    public Car getCar(@Name("vin") String vin);
	
    @Mutation
    public Car addCar(@Name("newCar") Car newCar);
	
    @Mutation
    public Car removeCar(String vin);
	
    @Mutation
    public Car replaceCar(Car newCar);
}
```

**Comment by t1** [comment]
I can't reproduce this! Maybe a newer version helps?

**Comment by t1** [comment]
If anybody can reproduce this, please give us a hint and reopen the issue.

**Comment by WhiteCat22** [comment]
When I free up I'll attempt to update and see if it still fails. If it still does, I'll push my project to github so you can grab it.
