### ISSUE TITLE
graphql schema creator throws java.lang.NullPointerException when Query return type has a List<T> or an array

### ISSUE THREAD

**Issue by okothhc** [smallrye/smallrye-graphql#740]
When graphql query has a return type that has a list or an array object in it, a null pointer exception is raised in io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:275)

**Sample code:**
@GraphQLAPI
class CoreResource {

@query("listxyz")
@description("Lists the xyz")
fun listXyz(@name("code") code: String) :
CompletionStage<ServerResponse<List>>
= xyzService.list()
}

A look at the source code https://github.com/smallrye/smallrye-graphql/blob/a3b2143c5671ccd5ad01b8dc1046f27af2d8b7ed/common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/ReferenceCreator.java#L355 which invokes getReference(direction, pat, null, null, parentObjectReference) passes null for Type methodType parameter.

The null that is passed in line 355 thus leads to null pointer exception being raised at line 275 https://github.com/smallrye/smallrye-graphql/blob/a3b2143c5671ccd5ad01b8dc1046f27af2d8b7ed/common/schema-builder/src/main/java/io/smallrye/graphql/schema/creator/ReferenceCreator.java#L275 when it is invoked.

Type typeInMethodCollection = methodType.asParameterizedType().arguments().get(0); (line 275 consumes methodType that was passed as null in line 355, thus null pointer is an obvious result)

**Expected behavior**
Line 355 should not pass null for methodType or it should invoke the right method that will not lead to NPE

**Actual behavior**
Null pointer Exception is raised.

**Quarkus version or git rev**
`<properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <kotlin.version>1.4.31</kotlin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.13.1.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.13.1.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>`

Build tool (ie. output of mvnw --version or gradlew --version)
Maven home: C:\Program Files\apache-maven-3.6.3\bin..
Java version: 11.0.9, vendor: GraalVM Community, runtime: C:\Program Files\graalvm-ce-java11-20.3.0
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
This fails. The variants for Array and Collections also fails.
@Query("listSubscriber") @Description("Lists the subscribers") fun listSubscriber(@Name("code") code: String) : CompletionStage<ServerResponse<List<SubscriberPayload>>> = subsciberService.list()

This works fine.
@Query("getSubscriberByCode") @Description("Gets the subscriber by assigned code") fun getSubscriberByCode(@Name("code") code: String) : ServerResponse<SubscriberPayload> = subsciberService.findByCode(code)

Caused by: java.lang.NullPointerException
at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:275)
at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:356)
at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:276)
at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:245)
at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:70)
at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:170)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
at java.base/java.lang.Thread.run(Thread.java:834)
at org.jboss.threads.JBossThread.run(JBossThread.java:501)

**Comment by phillip-kruger** [comment]
Thanks @okothhc ! @velias do you want to have a look ?

**Comment by velias** [comment]
Sorry for late reply, I was on other tasks. Can I ask what exactly are `CompletionStage`, `ServerResponse` and `SubscriberPayload`, which package they come from, are they classes or interfaces? I want to create reproducer in test, I found `java.util.concurrent.CompletionStage` interface, but not sure what exactly is `ServerResponse` and `SubscriberPayload` to make test correct.

**Comment by velias** [comment]
OK, I tried to chain one generic interfaces then List into it and then some object, and looks like I got same error `InterfaceWithOneGenericsParam<List<TestObject>>`.
When I replace `List` with my generic interface then everything looks good, so problem is probably related to presence of `List` there in the deeper chain. `List` at the top level is OK, same problem is also when I use GenericObject and use List inside of it. 
So I need to investigate why generics it is not resolved correctly if `List` is present somewhere deeper.

**Comment by velias** [comment]
I found exact place of the problem, but patch will be a bit more complex, as current code for building GraphQL schema expects Collections and arrays at top level only, they are not reflected in any way in `Reference` objects. So we probably need to extend `Reference` object somehow to keep info about nested collections/arrays, and then generate correct scheme (with correct Wrappers) for them. 
It is also related to bug #753 which reports problems around `@NonNull` annotations in generic collections and we have to make sure it works correctly even for these deeper nested collections.

**Comment by velias** [comment]
Problematic code:
`io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ClassInfo, List<? extends Type>, Direction, Reference)` causes NPE because it calls `getReference()` with `null` as `methodType` param. This can be patched easily, no more NPE, but generated GraphQL schema is not correct because of:
* `io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(Direction, Type, Type, Annotations, Reference)` returns `Reference` instance for `TestObject` type without any info that it is enclosed in `List` (same for array), which causes problem in `io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(Direction, FieldInfo, MethodInfo, Reference)`  where it adds only `TestObject` into schema, without `Wrapper` for the `List` or array. 
* Also name of the type in schema is incorrect `ClassWithOneGenericsParam_TestObject` - no any mention of List (or array) here which may cause collision if similar structure without list will be used in same endpoint also - this should be patched in `io.smallrye.graphql.schema.helper.TypeNameHelper.createParametrizedTypeNameExtension(Map<String, Reference>)` 

Proposed solution:
* Extend `Reference` object so it contains info that given type is enclosed in Collection or array. 
* Patch `createFieldForPojo` and `createParametrizedTypeNameExtension` to use this info to generate correct schema
* Make sure other parts of schema generation based on the `Reference` instances generate correct code (correct types for the schema etc)

This extension of the `Reference` should also somehow keep info about `@NonNull` annotation for that Collection or Array (not to be mixed with annotation for type inside of the colelction) to patch #753 

@phillip-kruger  WDYT?

**Comment by phillip-kruger** [comment]
Hi @velias - not sure if I follow the issue properly here. Can you talk me thought it using the model diagram (https://github.com/smallrye/smallrye-graphql/tree/main/common/schema-model) ?

**Comment by velias** [comment]
I'll try, but I'm not sure if I know that structure completely, and it looks a bit outdated as I do not see `Wrapper` in that schema ;-):
We have this generics structure `InterfaceWithOneGenericsParam<List<TestObject>>` returned from `Operation`. 
One `Field` in the `InterfaceWithOneGenericsParam` `Type` is generic and is type `List<TestObject>` in java thanks to that deeper generics definition. 
But `Reference` assigned to that `Field` is for java type `TestObject` only, and `Wrapper` for that `List` is not set to that `Filed` because info about it is not known in code where `Field` is created. We have only `Reference` here representing `TestObject` and parent `Reference` representing `InterfaceWithOneGenericsParam` where info about the `List` is not present at all. We also have jandex `methodType` and `fieldType` here but they represent generics type variables like `T` and there is not any way how to resolve them to that `List`. 

If `Operation' returns collection directly, like `List<TestObject>`, then info about `List` is available in the code where `Field` is created over jandex `methodType` or `fieldType` so `Wrapper` is created correctly for it. `Reference` for that `Field` represents `TestObject` also.

So I believe we have to extend `Reference` object to hold info that referenced type (`TestObject` in our case) is enclosed in `List` for this field, so this info is available in the code where `Field` is created (as jandex `methodType` and `fieldType` are not directly available here because our types are created thanks to that deeper generics structure).

Hope it makes more sense now, this is a bit hard to explain as whole schema generation is really complex stuff and generics added another layer of complexity here

**Comment by phillip-kruger** [comment]
Ok cool thanks. Let me update the diagram to include Wrapper. As far as I know Wrapper has a Wrapper, so we should be able to model this.

**Comment by velias** [comment]
Cool. But my general point is that info about Collections and arrays is not currently reflected in `Reference` object, for the top level the `Wrappers` are directly derived from jandex types. But this doesn't work for deeper generics structures now. So I'm thinking how to propagate necessary information to the code where `Wrapper` is really created for `Field`.

**Comment by phillip-kruger** [comment]
Ok, it's been I while since I looked at this, but I though Collections, Optional, Async stuff (ComplerableFuture etc) and other generics (?? not sure) are all "wrappers". Operations and Arguments are Fields, so it should also works for "top level". (If I understand you correctly). I remember I wanted to move the generic stuff out of model and into impl, and use the wrapper concept, but have not gotten around to that yet, maybe that is the problem ? Any generic element should be a wrapper. Maybe wrapper needs to be enhanced to hold more information to get this right ... ?
