### ISSUE TITLE
ClassCastException when using Temporal datatype on complex return object with asynchronous result processing

### ISSUE THREAD

**Issue by sacnoth** [smallrye/smallrye-graphql#779]
I'd like to asynchronously return a Temporal attribute from an object that was queried in an GraphQL service, but anytime I execute a query to retrieve the value I get a ClassCastException and the query result will not get formatted as expected.

GraphQL service:
```Java
package me.sacnoth.smallrye.graphql.completablefuturetemporalbug;

import org.eclipse.microprofile.graphql.DateFormat;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Query;

import java.time.ZonedDateTime;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

@GraphQLApi
public class TestGraphQLService {

    @Query
    public CompletionStage<MyTime> time() {
        return CompletableFuture.completedFuture(new MyTime());
    }

    private static class MyTime {

        @DateFormat("yyyy")
        private CompletionStage<ZonedDateTime> getNow() {
            return CompletableFuture.completedFuture(ZonedDateTime.now());
        }
    }
}
```

Query:
```GraphQL
{
  time {
    now
  }
}
```

Exception:
```
2021-05-06 14:30:48,761 ERROR [io.sma.graphql] (vert.x-worker-thread-1) SRGQL014000: Unable to transform data: java.lang.ClassCastException: class java.util.concurrent.CompletableFuture cannot be cast to class java.time.temporal.Temporal (java.util.concurrent.CompletableFuture and java.time.temporal.Temporal are in module java.base of loader 'bootstrap')
	at io.smallrye.graphql.transformation.DateTransformer.out(DateTransformer.java:28)
	at io.smallrye.graphql.transformation.Transformer.out(Transformer.java:34)
	at io.smallrye.graphql.execution.datafetcher.helper.FieldHelper.singleTransform(FieldHelper.java:48)
	at io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.recursiveTransform(AbstractHelper.java:78)
	at io.smallrye.graphql.execution.datafetcher.helper.FieldHelper.transformResponse(FieldHelper.java:32)
	at io.smallrye.graphql.execution.datafetcher.PropertyDataFetcher.get(PropertyDataFetcher.java:36)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:646)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390)
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:205)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at io.smallrye.context.CompletableFutureWrapper.thenApply(CompletableFutureWrapper.java:210)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:204)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
	at graphql.execution.Execution.executeOperation(Execution.java:165)
	at graphql.execution.Execution.execute(Execution.java:104)
	at graphql.GraphQL.execute(GraphQL.java:557)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
	at graphql.GraphQL.executeAsync(GraphQL.java:446)
	at graphql.GraphQL.execute(GraphQL.java:377)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:131)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:169)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:112)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:93)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-05-06 14:30:48,762 ERROR [io.sma.graphql] (vert.x-worker-thread-1) SRGQL014000: Unable to transform data: io.smallrye.graphql.transformation.TransformException: java.lang.ClassCastException: class java.util.concurrent.CompletableFuture cannot be cast to class java.time.temporal.Temporal (java.util.concurrent.CompletableFuture and java.time.temporal.Temporal are in module java.base of loader 'bootstrap')
	at io.smallrye.graphql.transformation.Transformer.out(Transformer.java:37)
	at io.smallrye.graphql.execution.datafetcher.helper.FieldHelper.singleTransform(FieldHelper.java:48)
	at io.smallrye.graphql.execution.datafetcher.helper.AbstractHelper.recursiveTransform(AbstractHelper.java:78)
	at io.smallrye.graphql.execution.datafetcher.helper.FieldHelper.transformResponse(FieldHelper.java:32)
	at io.smallrye.graphql.execution.datafetcher.PropertyDataFetcher.get(PropertyDataFetcher.java:36)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:646)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390)
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:205)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at io.smallrye.context.CompletableFutureWrapper.thenApply(CompletableFutureWrapper.java:210)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:204)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
	at graphql.execution.Execution.executeOperation(Execution.java:165)
	at graphql.execution.Execution.execute(Execution.java:104)
	at graphql.GraphQL.execute(GraphQL.java:557)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
	at graphql.GraphQL.executeAsync(GraphQL.java:446)
	at graphql.GraphQL.execute(GraphQL.java:377)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:131)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:169)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:112)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:93)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class java.util.concurrent.CompletableFuture cannot be cast to class java.time.temporal.Temporal (java.util.concurrent.CompletableFuture and java.time.temporal.Temporal are in module java.base of loader 'bootstrap')
	at io.smallrye.graphql.transformation.DateTransformer.out(DateTransformer.java:28)
	at io.smallrye.graphql.transformation.Transformer.out(Transformer.java:34)
	... 37 more
```

Output:
```JSON
{
  "data": {
    "time": {
      "now": "2021-05-06T14:24:03.909369300+02:00[Europe/Berlin]"
    }
  }
}
```

Expected output:
```JSON
{
  "data": {
    "time": {
      "now": "2021"
    }
  }
}
```

POM:
```XML
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>me.sacnoth.smallrye.graphql.completablefuturetemporalbug</groupId>
  <artifactId>SmallRye-GraphQL-CompletableFutureTemporalBug</artifactId>
  <version>1.0.0</version>

  <name>SmallRye-GraphQL-CompletableFutureTemporalBug</name>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>

    <quarkus-plugin.version>1.13.3.Final</quarkus-plugin.version>
    <quarkus.platform.version>1.13.3.Final</quarkus.platform.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-universe-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- region quarkus -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-graphql</artifactId>
    </dependency>
    <!-- endregion -->
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by phillip-kruger** [comment]
Hi @sacnoth , can you share a reproducer I can look at ?

**Comment by sacnoth** [comment]
Do you mean the project I used to reproduce the error? Yes, I can share it:
[SmallRye-GraphQL-CompletableFutureTemporalBug.zip](https://github.com/smallrye/smallrye-graphql/files/6434748/SmallRye-GraphQL-CompletableFutureTemporalBug.zip)

You can launch this easily in the Quarkus dev-mode: `mvn compile quarkus:dev` and access the local dev environment at: http://localhost:8080/q/graphql-ui/ to execute the query I supplied in the ticket.

**Comment by phillip-kruger** [comment]
Thanks :) I'll have a look a.s.a.p

**Comment by phillip-kruger** [comment]
Ok, so here the problem.

The response object needs to be a POJO (i.e Java Bean, getter/setter) and does not support CompletionStage on fields in the POJO. Mostly because the DataFetcher would not know how to fetch that. You can however get what you want by using a `Source` field like this: 

```
@GraphQLApi
public class TestGraphQLService {

    @Query
    public CompletionStage<MyTime> time() {
        return CompletableFuture.completedFuture(new MyTime());
    }

    @DateFormat("yyyy")
    public CompletionStage<ZonedDateTime> getNow(@Source MyTime myTime) {
        return CompletableFuture.completedFuture(ZonedDateTime.now());
    }
    
    private static class MyTime {

    }
}
```

**Comment by phillip-kruger** [comment]
Let me know if this works for you and if we can close this.

**Comment by sacnoth** [comment]
Yes, your provided solution with the @Source field would work. Thanks for your quick response!

It just seemed odd to me, that it would only fail on Temporal types, as other datatypes (Integer, BigDecimal, String, ...) worked flawlessly, as demonstrated here:

```Java
@GraphQLApi
public class TestGraphQLService {

    @Query
    public CompletionStage<MyNumbers> numbers() {
        return CompletableFuture.completedFuture(new MyNumbers());
    }

    private static class MyNumbers {

        private CompletionStage<BigInteger> getTen() {
            return CompletableFuture.completedFuture(BigInteger.TEN);
        }
    }
}

```

Query:
```GraphQL
query{
  numbers{
    ten
  }
}
```

Result:
```JSON
{
  "data": {
    "numbers": {
      "ten": 10
    }
  }
}
```

Reproducer: [WorkingCompletionStageOnObject.zip](https://github.com/smallrye/smallrye-graphql/files/6436198/WorkingCompletionStageOnObject.zip)

If asynchronous operations on objects are not supposed to work you can close this ticket and I thank you for your explanation 🙂.

**Comment by phillip-kruger** [comment]
We can always make them work, but that is currently outside of the spec. I think the problem is the `DateFormat`. Try doing a `NumberFormat` on your number example. That should also fail

**Comment by sacnoth** [comment]
Yes, that will fail as well. I will close this ticket as the behavior I'm using is unsupported.
