### ISSUE TITLE
GraphQLUI Data Fetching Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by talbiislam96** [smallrye/smallrye-graphql#850]
Trying to test my GraphQL API on GraphQlUI , I get a fetching data error every time I run the query.
 this is the api:

``` 

    private UUID getCurrentUserId() {
        return UUID.fromString(currentContextRequest.getUserProfile().getId());
    }

    @Inject
    TimeSheetGraphQlService timeSheetGraphQlService;

   @Query("allSheets")
   @Description("Get all sheets for user by year and week")
    public List <MissionTimeSheets> getAllSheetsForUser(int year, int week){
       return timeSheetGraphQlService.getTimesheetUser(year,week,getCurrentUserId().toString());

   }



```

The service 

``` 

public List<MissionTimeSheets> getTimesheetUser(int year, int week, String userId) {

        List <MissionTimeSheets> missionTimeSheetsList = new ArrayList<>();

        List<HolidaysClientDto> listUserHoliday = (List<HolidaysClientDto>) getHolidayByUserId(userId);
        List<MissionDto> activeMissionsList = getMissionsForUser(year, week, userId);
        HolidaysClientDto holidaysClientDto = new HolidaysClientDto();
        MissionTimeSheets mdto = new MissionTimeSheets();


        TimeSheetClientDto dto = getTimesheetQuery(year, week);
        if (dto == null || dto.getCaseTimeSheetList() == null || dto.getCaseTimeSheetList().isEmpty()) {
            //if (!listUserHoliday.isEmpty()) {
            //listUserHoliday.forEach(
            //holiday -> {
            //if (holiday.getStatus().equals(HolidayStatus.ACCEPTED)) {
            //code couleur

            // } else if (holiday.getStatus().equals(HolidayStatus.PENDING)) {
            //code couleur

            // }

            // }


            //);

           // return mapTimesheet;
            return missionTimeSheetsList;

        } else {
            activeMissionsList.forEach(
                    mission -> {
                        List<CaseTimesheetDto> cctUserList = new ArrayList<>();
                        dto.getCaseTimeSheetList().forEach(
                                caseTimesheetClientDto -> {
                                    if (mission.getId().toString().equals(caseTimesheetClientDto.getMissionId())) {
                                        if (!listUserHoliday.isEmpty()) {
                                            listUserHoliday.forEach(
                                                    holiday -> {
                                                        String holidayStatus = verifyHolidayStatus(holiday);
                                                        String holidayPartDay = verifyHolidayPartDay(holiday);
                                                        CaseTimesheetDto ctd = buildFromCaseTimesheetClientDto(caseTimesheetClientDto);
                                                        ctd.setHolidayPartDay(holidayPartDay);
                                                        ctd.setHolidaysStatus(holidayStatus);
                                                        cctUserList.add(ctd);

                                                    }
                                            );


                                        }

                                    }
                                }
                        );
                      //  mapTimesheet.put(mission, cctUserList);
                        mdto.setTimesheets(cctUserList);
                        mdto.setMission(mission);
                        missionTimeSheetsList.add(mdto);
                    }
            );


        }

        return missionTimeSheetsList;

    }




```

The api returns an object that contains key-value pairs since maps are not supported yet in graphQl.
 
Here's the object that the api is supposed to return

``` 
@Getter
@Setter
public class MissionTimeSheets {
    MissionDto mission;
    List<CaseTimesheetDto> timesheets;
}

```

The Query : 

``` 
query allhSheets {
  allSheets(year:2021,week:1) {
    mission{
      startDate
      endDate
    }
    
    timesheets{
      day
      entriesTimeSheet
    }
  }
}

```
Current behavior :

``` 
2021-06-09 10:51:03,160 ERROR [io.sma.graphql] (vert.x-worker-thread-3) SRGQL012000: Data Fetching Error: java.lang.NullPointerException
        at tn.wecraft.helium.api.trackingtime.weeklysheet.v1.resources.TimeSheetGraphQlResource.getCurrentUserId(TimeSheetGraphQlResource.java:21)
        at tn.wecraft.helium.api.trackingtime.weeklysheet.v1.resources.TimeSheetGraphQlResource.getAllSheetsForUser(TimeSheetGraphQlResource.java:30)
        at tn.wecraft.helium.api.trackingtime.weeklysheet.v1.resources.TimeSheetGraphQlResource_Subclass.getAllSheetsForUser$$superaccessor1(TimeSheetGraphQlResource_Subclass.zig:245)
        at tn.wecraft.helium.api.trackingtime.weeklysheet.v1.resources.TimeSheetGraphQlResource_Subclass$$function$$1.apply(TimeSheetGraphQlResource_Subclass$$function$$1.zig:45)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at tn.wecraft.helium.api.trackingtime.weeklysheet.v1.resources.TimeSheetGraphQlResource_Subclass.getAllSheetsForUser(TimeSheetGraphQlResource_Subclass.zig:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.smallrye.graphql.execution.datafetcher.helper.ReflectionHelper.invoke(ReflectionHelper.java:84)
        at io.smallrye.graphql.execution.datafetcher.DefaultDataFetcher.invokeAndTransform(DefaultDataFetcher.java:38)
        at io.smallrye.graphql.execution.datafetcher.AbstractDataFetcher.get(AbstractDataFetcher.java:62)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
        at graphql.execution.Execution.executeOperation(Execution.java:165)
        at graphql.execution.Execution.execute(Execution.java:104)
        at graphql.GraphQL.execute(GraphQL.java:557)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
        at graphql.GraphQL.executeAsync(GraphQL.java:446)
        at graphql.GraphQL.execute(GraphQL.java:377)
        at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:131)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:176)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:169)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handlePost(SmallRyeGraphQLExecutionHandler.java:112)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doHandle(SmallRyeGraphQLExecutionHandler.java:93)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:64)
        at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.handle(SmallRyeGraphQLExecutionHandler.java:37)
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)


```
Lastly, this is the error that I get as a result while running the query on GraphQlUI:

``` 
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allSheets"
      ],
      "extensions": {
        "exception": "java.lang.NullPointerException",
        "classification": "DataFetchingException",
        "code": "null-pointer"
      }
    }
  ],
  "data": {
    "allSheets": null
  }
}



```

I would appreciate your insight, as am totally new to GraphQl and Quarkus , I really don't know what seems to be wrong is it the api , the service , the query or maybe all three of them :( thank you in advance and happy Coding .

**Comment by phillip-kruger** [comment]
It seems like currentContextRequest is `null`. Where does that come from ?
