### ISSUE TITLE
Error when app contains only queries - no mutations

### ISSUE THREAD

**Issue by andymc12** [smallrye/smallrye-graphql#86]
I have a simple "echo" app that contains a single query.  When I run this app in OpenLiberty using graphiql HTML client, I see this error message before I run any queries:

```
Error: Mutation fields must be an object with field names as keys or a function which returns such an object.
    at invariant (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:24809:11)
    at defineFieldMap (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:28078:27)
    at GraphQLObjectType.getFields (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:28035:44)
    at typeMapReducer (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:29752:25)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:29641:34)
    at buildClientSchema (https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:31049:10)
    at https://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:2131:55
```

I think the implementation must be creating a Mutation type even if there are no `@Mutation`-annotated methods.  I am planning to investigate.

**Comment by andymc12** [comment]
Here is the generated schema:
```
$ curl http://localhost:9080/echoService/graphql/schema.graphql
"Mutation root"
type Mutation {
}

"Query root"
type Query {
  echo(word: String): String
}
```
