### ISSUE TITLE
No class info found for parametrizedParentType name [java.util.HashSet], when build

### ISSUE THREAD

**Issue by pipinet** [smallrye/smallrye-graphql#874]
```java
import java.util.HashSet;

public class LocationTags extends HashSet<LocationTag> {

}
```
```java

import org.eclipse.microprofile.graphql.Type;
import qw.rs.core.domain.models.LocationTags;

@Type("Location")
public class LocationPayload {
    private String id;
    private String name;
    private LocationTags tags;
  ...getter setter
```

```log
2021-06-26 19:19:38,237 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: io.smallrye.graphql.schema.SchemaBuilderException: No class info found for parametrizedParentType name [java.util.HashSet]
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:288)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForPojoField(ReferenceCreator.java:149)
        at io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:128)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:63)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:70)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:34)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:32)
        at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:219)
        at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:153)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:121)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:86)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:169)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:401)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:269)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:84)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:409)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:58)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:89)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: io.smallrye.graphql.schema.SchemaBuilderException: No class info found for parametrizedParentType name [java.util.HashSet]
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:288)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForPojoField(ReferenceCreator.java:149)
        at io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:128)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:63)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:70)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:34)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:32)
        at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:219)
        at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:153)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:121)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:86)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:169)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:153)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:399)
        ... 9 more
Caused by: io.smallrye.graphql.schema.SchemaBuilderException: No class info found for parametrizedParentType name [java.util.HashSet]
        at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:288)
        at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForPojoField(ReferenceCreator.java:149)
        at io.smallrye.graphql.schema.creator.FieldCreator.createFieldForPojo(FieldCreator.java:128)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.addFields(TypeCreator.java:63)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:70)
        at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:34)
        at io.smallrye.graphql.schema.creator.type.AbstractCreator.create(AbstractCreator.java:32)
        at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:219)
        at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:153)
        at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:121)
        at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:86)
        at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:169)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by phillip-kruger** [comment]
Hi @pipinet - do you have a small reproducer ?
