### ISSUE TITLE
one wildfly 2 war files with GraphQL Context throws NullPointerException

### ISSUE THREAD

**Issue by verboomp** [smallrye/smallrye-graphql#955]
I have a Wildfly 23 running with the GraphQL feature pack from https://github.com/wildfly-extras/wildfly-graphql-feature-pack. On this Wildfly I have installed 2 war files with a GraphQL Service similar to this:   

@GraphQLApi
@RequestScoped
public class GraphQLResource {

	@Inject
	private Context context;

        @Query("users")
	@Description("Get a list with users")
	public List<UserDtoValue> users() {
                var fields = context.getSelectedFields();
		return new ArrayList<>();
	}

}

I use the fields to create a  JPA criteria query . Both war files run fine on their own but when I deploy them both on one Wildfly server than  one of the war files GraphQL service works fine but the second one throws an  error on getSelectedFields method :

2021-08-05 11:54:13,135 ERROR [io.smallrye.graphql] (default task-6) SRGQL012000: Data Fetching Error: java.lang.NullPointerException
	at io.smallrye.graphql@4.8//io.smallrye.graphql.execution.context.SmallRyeContext.isSourceField(SmallRyeContext.java:278)
	at io.smallrye.graphql@4.8//io.smallrye.graphql.execution.context.SmallRyeContext.toJsonArrayBuilder(SmallRyeContext.java:253)
	at io.smallrye.graphql@4.8//io.smallrye.graphql.execution.context.SmallRyeContext.getSelectedFields(SmallRyeContext.java:166)
	at io.smallrye.graphql.api//io.smallrye.graphql.api.Context.getSelectedFields(Context.java:181)
	at io.smallrye.graphql@4.8//io.smallrye.graphql.cdi.producer.SmallRyeContextAccessorProxy.getSelectedFields(SmallRyeContextAccessorProxy.java:156)
	at io.smallrye.graphql@4.8//io.smallrye.graphql.api.Context1015796477$Proxy$_$$_WeldClientProxy.getSelectedFields(Unknown Source)
	

Is there something I am missing or is it not possible to have two war's with smallrye GraphQL running on the same server?

**Comment by jmartisk** [comment]
Hi, thanks for reporting this. We try to make sure that multiple WARs can be deployed at the same time, but there have been some issues with it, so this may be another one. I'll try to reproduce this and get back to you

**Comment by jmartisk** [comment]
Right so the problem is, as usual, in a static field: https://github.com/smallrye/smallrye-graphql/blob/1.3.1/server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContext.java#L48

This field is (unintentionally) shared between the two (or more) deployed applications, and therefore at least one of them necessarily sees a 'wrong' value. This will need to be turned into a map keyed by the application's context class loader, or something. I'll prepare a fix

**Comment by verboomp** [comment]
hi,

great work and very fast.

Thank you in advance.

**Comment by jmartisk** [comment]
So this should be fixed in WF feature pack 1.4.1 - I'll release that soon after SmallRye GraphQL 1.3.2 is out. Enjoy!
