### ISSUE TITLE
maven-plugin fails to execute since MavenConfig can't be loaded by the service loader

### ISSUE THREAD

**Issue by shmulik-klein** [smallrye/smallrye-graphql#963]
Seems like the recent change for config (261310802b7062f1ecbd86fc51d3ea2a512a09d8) broke the maven plugin, since the service provider `io.smallrye.graphql.mavenplugin.GenerateSchemaMojo.MavenConfig` can't be loaded.

The following exception is thrown:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.util.ServiceConfigurationError: io.smallrye.graphql.spi.config.Config: Provider io.smallrye.graphql.mavenplugin.GenerateSchemaMojo.MavenConfig not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1306)
	at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1297)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at io.smallrye.graphql.spi.config.Config.init(Config.java:27)
	at io.smallrye.graphql.spi.config.Config.<clinit>(Config.java:22)
	at io.smallrye.graphql.execution.event.EventEmitter.<init>(EventEmitter.java:32)
	at io.smallrye.graphql.execution.event.EventEmitter.getInstance(EventEmitter.java:28)
	at io.smallrye.graphql.bootstrap.Bootstrap.<init>(Bootstrap.java:88)
	at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:103)
	at io.smallrye.graphql.mavenplugin.GenerateSchemaMojo.generateSchema(GenerateSchemaMojo.java:165)
	at io.smallrye.graphql.mavenplugin.GenerateSchemaMojo.execute(GenerateSchemaMojo.java:110)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	... 7 more
```

The reason for that is that a service provider can't be defined as an inner class - [ServiceLoader JavaDoc ](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/ServiceLoader.html)

**Comment by shmulik-klein** [comment]
Please note, without confirming it, I believe that the Gradle plugin also suffers from the same issue.
