### ISSUE TITLE
Query returning Multi<O> fails 

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#968]
When a `@Query`-method returns `Multi<O>`, the returned Multi is not handled/unpacked correctly, resulting in
```
java.lang.IllegalArgumentException: Can not set final java.lang.String field org.acme.Company.id to io.smallrye.mutiny.operators.multi.MultiFlatMapOnFailure
       ...
        at java.base/java.lang.reflect.Field.get(Field.java:419)
        at io.smallrye.graphql.execution.datafetcher.FieldDataFetcher$FieldAccessor.get(FieldDataFetcher.java:118)
        at io.smallrye.graphql.execution.datafetcher.FieldDataFetcher.get(FieldDataFetcher.java:66)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
        at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:646)
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:438)
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390)
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:205)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2164)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:204)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
        at graphql.execution.Execution.executeOperation(Execution.java:165)
        at graphql.execution.Execution.execute(Execution.java:104)
        at graphql.GraphQL.execute(GraphQL.java:557)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482)
        at graphql.GraphQL.executeAsync(GraphQL.java:446)
        at graphql.GraphQL.execute(GraphQL.java:377)
        at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:119)
```
With query 
```
query {
  company {
    name
    id
    something {
      something
    }
  }
}
```
Changing method to `Uni<List<O>>` returns the expected result.

Stepping through the code a bootup I see that `DataFetcherFactory.get(operation)`  does return a `MultiDataFetcher`, but neither `onItem()` or `onFailure()` is called.

Is reproducible on Quarkus 2.1.1 (smallrye-graphql 1.2.8) with
```java
@GraphQLApi
public class CompanyResource {

    @Query
    public Multi<Company> hello() {
        return Multi.createFrom().items(
                new Company("A", "AAA"),
                new Company("B", "BBB"),
                new Company("C", "CCC"),
                new Company("D", "DDD")
        );
    }

    public Something getSomething(@Source Company company) {
        return new Something("Something " + company.name);
    }
   
    public static class Company {
        public final String name;
        public final String id;

        public Company(String name, String id) {
            this.name = name;
            this.id = id;
        }
    }
    public static class Something {
        public final String something;

        public Something(String something) {
            this.something = something;
        }
    }
}
```

**Comment by phillip-kruger** [comment]
Hi @computerlove . Multi is not supported for `Query`. I am not sure that it should ? At the moment it's supported for `@Subscription`

**Comment by computerlove** [comment]
Ok, wasn't sure whether it should be supported. 
Closing issue.

**Comment by fp-smartlogic** [comment]
It would be nice to support Multi, not only Uni. That would solve the issue of streaming huge responses and avoiding memory consumption.

**Comment by jmartisk** [comment]
How do you expect that to work? 
To stream huge (potentially infinitely large) responses, you should use subscriptions, these run over websockets.

If we allowed to return a `Multi` from a query, then the processing would still have to wait for all the items to arrive before we could write the response, so it wouldn't solve the memory consumption issue.

I don't think it's possible to start writing the response on-the-fly while still waiting for more items to arrive:
- data and errors will appear in an unordered fashion, but you can't append into the `errors` field while you haven't finished the `data` field
- if there are multiple queries invoked by a single request, that makes it even worse, because you can't write data for one query before you finish the other query

Even if we were able to overcome this and solve the memory consumption issue on the server, a gigantic HTTP response would still overwhelm the client. For these cases, subscriptions should be used, where items are  processed as a stream.
